//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PwC.C4.Configuration.WcfSettings;

namespace ApplicationCenter.Model
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Application", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class Application : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ActiveFlagField;

        private string ApplicationCodeField;

        private System.Guid ApplicationIDField;

        private string ApplicationNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveFlag
        {
            get
            {
                return this.ActiveFlagField;
            }
            set
            {
                this.ActiveFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationCode
        {
            get
            {
                return this.ApplicationCodeField;
            }
            set
            {
                this.ApplicationCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationID
        {
            get
            {
                return this.ApplicationIDField;
            }
            set
            {
                this.ApplicationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName
        {
            get
            {
                return this.ApplicationNameField;
            }
            set
            {
                this.ApplicationNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationRole", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class ApplicationRole : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ActiveFlagField;

        private string ApplicationCodeField;

        private System.Guid RoleIDField;

        private string RoleNameField;

        private string RoleTypeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveFlag
        {
            get
            {
                return this.ActiveFlagField;
            }
            set
            {
                this.ActiveFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationCode
        {
            get
            {
                return this.ApplicationCodeField;
            }
            set
            {
                this.ApplicationCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleType
        {
            get
            {
                return this.RoleTypeField;
            }
            set
            {
                this.RoleTypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationMenu", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class ApplicationMenu : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ActiveFlagField;

        private string ApplicationCodeField;

        private System.Guid MenuIDField;

        private string MenuNameField;

        private int MenuOrderField;

        private string MenuTargetField;

        private string MenuURLField;

        private System.Nullable<System.Guid> ParentMenuIDField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveFlag
        {
            get
            {
                return this.ActiveFlagField;
            }
            set
            {
                this.ActiveFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationCode
        {
            get
            {
                return this.ApplicationCodeField;
            }
            set
            {
                this.ApplicationCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MenuID
        {
            get
            {
                return this.MenuIDField;
            }
            set
            {
                this.MenuIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuName
        {
            get
            {
                return this.MenuNameField;
            }
            set
            {
                this.MenuNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuOrder
        {
            get
            {
                return this.MenuOrderField;
            }
            set
            {
                this.MenuOrderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuTarget
        {
            get
            {
                return this.MenuTargetField;
            }
            set
            {
                this.MenuTargetField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuURL
        {
            get
            {
                return this.MenuURLField;
            }
            set
            {
                this.MenuURLField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentMenuID
        {
            get
            {
                return this.ParentMenuIDField;
            }
            set
            {
                this.ParentMenuIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "User", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ApplicationCenter.Model.CurrentUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ApplicationCenter.Model.SSOTokenUser))]
    internal partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ActiveFlagField;

        private string AdditionUserIDField;

        private string EmailAddressField;

        private string MobileNoField;

        private int RootGroupIDField;

        private string UserIDField;

        private string UserNameField;
        
        private string UserTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveFlag
        {
            get
            {
                return this.ActiveFlagField;
            }
            set
            {
                this.ActiveFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionUserID
        {
            get
            {
                return this.AdditionUserIDField;
            }
            set
            {
                this.AdditionUserIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo
        {
            get
            {
                return this.MobileNoField;
            }
            set
            {
                this.MobileNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RootGroupID
        {
            get
            {
                return this.RootGroupIDField;
            }
            set
            {
                this.RootGroupIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CurrentUser", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class CurrentUser : ApplicationCenter.Model.User
    {

        private ApplicationCenter.Model.ApplicationMenu[] MenusField;

        private ApplicationCenter.Model.ApplicationRole[] RolesField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApplicationCenter.Model.ApplicationMenu[] Menus
        {
            get
            {
                return this.MenusField;
            }
            set
            {
                this.MenusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApplicationCenter.Model.ApplicationRole[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SSOTokenUser", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class SSOTokenUser : ApplicationCenter.Model.User
    {

        private System.DateTime ExpirationDateField;

        private string SSOTicketField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSOTicket
        {
            get
            {
                return this.SSOTicketField;
            }
            set
            {
                this.SSOTicketField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationAuthenticationMethod", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class ApplicationAuthenticationMethod : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int AppAuthMethodIDField;

        private string ApplicationCodeField;

        private ApplicationCenter.Model.AuthenticationMethod AuthMethodField;

        private string AutoLoginField;

        private int MethodIDField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppAuthMethodID
        {
            get
            {
                return this.AppAuthMethodIDField;
            }
            set
            {
                this.AppAuthMethodIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationCode
        {
            get
            {
                return this.ApplicationCodeField;
            }
            set
            {
                this.ApplicationCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApplicationCenter.Model.AuthenticationMethod AuthMethod
        {
            get
            {
                return this.AuthMethodField;
            }
            set
            {
                this.AuthMethodField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoLogin
        {
            get
            {
                return this.AutoLoginField;
            }
            set
            {
                this.AutoLoginField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MethodID
        {
            get
            {
                return this.MethodIDField;
            }
            set
            {
                this.MethodIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AuthenticationMethod", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class AuthenticationMethod : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CAPACHAFlagField;

        private string MethodCodeField;

        private int MethodIDField;

        private string MethodNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAPACHAFlag
        {
            get
            {
                return this.CAPACHAFlagField;
            }
            set
            {
                this.CAPACHAFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodCode
        {
            get
            {
                return this.MethodCodeField;
            }
            set
            {
                this.MethodCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MethodID
        {
            get
            {
                return this.MethodIDField;
            }
            set
            {
                this.MethodIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationAuthenticationMethodWebLogin", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class ApplicationAuthenticationMethodWebLogin : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int AppAuthMethodIDField;

        private string LoginUIField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppAuthMethodID
        {
            get
            {
                return this.AppAuthMethodIDField;
            }
            set
            {
                this.AppAuthMethodIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginUI
        {
            get
            {
                return this.LoginUIField;
            }
            set
            {
                this.LoginUIField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TicketStore", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class TicketStore : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime CreateDateField;

        private double ExpectedDurationField;

        private System.Guid TicketField;

        private string TicketTypeField;

        private string UserIDField;

        private bool VerifiedField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ExpectedDuration
        {
            get
            {
                return this.ExpectedDurationField;
            }
            set
            {
                this.ExpectedDurationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Ticket
        {
            get
            {
                return this.TicketField;
            }
            set
            {
                this.TicketField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketType
        {
            get
            {
                return this.TicketTypeField;
            }
            set
            {
                this.TicketTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Verified
        {
            get
            {
                return this.VerifiedField;
            }
            set
            {
                this.VerifiedField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SMSStore", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class SMSStore : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime CreateDateField;

        private double ExpectedDurationField;

        private string SMSCodeField;

        private System.Guid SMSIDField;

        private string SMSTypeField;

        private int SendResultField;

        private bool SentField;

        private string UserIDField;

        private bool VerifiedField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ExpectedDuration
        {
            get
            {
                return this.ExpectedDurationField;
            }
            set
            {
                this.ExpectedDurationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMSCode
        {
            get
            {
                return this.SMSCodeField;
            }
            set
            {
                this.SMSCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SMSID
        {
            get
            {
                return this.SMSIDField;
            }
            set
            {
                this.SMSIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMSType
        {
            get
            {
                return this.SMSTypeField;
            }
            set
            {
                this.SMSTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SendResult
        {
            get
            {
                return this.SendResultField;
            }
            set
            {
                this.SendResultField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sent
        {
            get
            {
                return this.SentField;
            }
            set
            {
                this.SentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Verified
        {
            get
            {
                return this.VerifiedField;
            }
            set
            {
                this.VerifiedField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AppCenterKeyValuePair", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class AppCenterKeyValuePair : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string KeyField;

        private string ValueField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "vwMenuRole", Namespace = "http://schemas.datacontract.org/2004/07/ApplicationCenter.Model")]
    internal partial class vwMenuRole : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ActiveFlagField;

        private string ApplicationCodeField;

        private int AuthorizationIDField;

        private string CreatedByField;

        private System.DateTime CreatedDateField;

        private string LastUpdatedByField;

        private System.DateTime LastUpdatedDateField;

        private string MenuDescriptionField;

        private System.Guid MenuIDField;

        private string MenuNameField;

        private int MenuOrderField;

        private string MenuURLField;

        private System.Nullable<System.Guid> ParentMenuIDField;

        private System.Guid RoleIDField;

        private string RoleNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveFlag
        {
            get
            {
                return this.ActiveFlagField;
            }
            set
            {
                this.ActiveFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationCode
        {
            get
            {
                return this.ApplicationCodeField;
            }
            set
            {
                this.ApplicationCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthorizationID
        {
            get
            {
                return this.AuthorizationIDField;
            }
            set
            {
                this.AuthorizationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy
        {
            get
            {
                return this.LastUpdatedByField;
            }
            set
            {
                this.LastUpdatedByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuDescription
        {
            get
            {
                return this.MenuDescriptionField;
            }
            set
            {
                this.MenuDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MenuID
        {
            get
            {
                return this.MenuIDField;
            }
            set
            {
                this.MenuIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuName
        {
            get
            {
                return this.MenuNameField;
            }
            set
            {
                this.MenuNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuOrder
        {
            get
            {
                return this.MenuOrderField;
            }
            set
            {
                this.MenuOrderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuURL
        {
            get
            {
                return this.MenuURLField;
            }
            set
            {
                this.MenuURLField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentMenuID
        {
            get
            {
                return this.ParentMenuIDField;
            }
            set
            {
                this.ParentMenuIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IApplicationService")]
internal interface IApplicationService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetAllApplicationList", ReplyAction = "http://tempuri.org/IApplicationService/GetAllApplicationListResponse")]
    ApplicationCenter.Model.Application[] GetAllApplicationList();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationList", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationListResponse")]
    ApplicationCenter.Model.Application[] GetApplicationList(string userid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetUserAllApplicationList", ReplyAction = "http://tempuri.org/IApplicationService/GetUserAllApplicationListResponse")]
    ApplicationCenter.Model.Application[] GetUserAllApplicationList(string userid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationRoleListByCode", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationRoleListByCodeResponse")]
    ApplicationCenter.Model.ApplicationRole[] GetApplicationRoleListByCode(string applicationcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationRoleListByID", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationRoleListByIDResponse")]
    ApplicationCenter.Model.ApplicationRole[] GetApplicationRoleListByID(System.Guid applicationid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationRoleByCodeAndMenuID", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationRoleByCodeAndMenuIDResponse")]
    ApplicationCenter.Model.ApplicationRole[] GetApplicationRoleByCodeAndMenuID(string applicationcode, System.Guid menuid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationMenuByCode", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationMenuByCodeResponse")]
    ApplicationCenter.Model.ApplicationMenu[] GetApplicationMenuByCode(string applicationcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationMenuByID", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationMenuByIDResponse")]
    ApplicationCenter.Model.ApplicationMenu[] GetApplicationMenuByID(System.Guid applicationid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetUserListByRoleID", ReplyAction = "http://tempuri.org/IApplicationService/GetUserListByRoleIDResponse")]
    ApplicationCenter.Model.User[] GetUserListByRoleID(System.Guid roleid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationAuthMethodByID", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationAuthMethodByIDResponse")]
    ApplicationCenter.Model.ApplicationAuthenticationMethod GetApplicationAuthMethodByID(System.Guid applicationid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationAuthMethodByCode", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationAuthMethodByCodeResponse")]
    ApplicationCenter.Model.ApplicationAuthenticationMethod GetApplicationAuthMethodByCode(string applicationcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicaitonAuthenticationMethodWebLogin" +
        "", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicaitonAuthenticationMethodWebLogin" +
        "Response")]
    ApplicationCenter.Model.ApplicationAuthenticationMethodWebLogin GetApplicaitonAuthenticationMethodWebLogin(int appauthmethodid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/UserAuthentication", ReplyAction = "http://tempuri.org/IApplicationService/UserAuthenticationResponse")]
    string UserAuthentication(string userloginaccount, string password, string authenticationmethod);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/UserAuthenticationWithAppCode", ReplyAction = "http://tempuri.org/IApplicationService/UserAuthenticationWithAppCodeResponse")]
    string UserAuthenticationWithAppCode(string userloginaccount, string password, string appcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/TwoFactorsAuthentication", ReplyAction = "http://tempuri.org/IApplicationService/TwoFactorsAuthenticationResponse")]
    bool TwoFactorsAuthentication(string userid, string twofactorscode, string authenticationmethod);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetCurrentUser", ReplyAction = "http://tempuri.org/IApplicationService/GetCurrentUserResponse")]
    ApplicationCenter.Model.CurrentUser GetCurrentUser(string userid, string applicationcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetCurrentUserWithHashCode", ReplyAction = "http://tempuri.org/IApplicationService/GetCurrentUserWithHashCodeResponse")]
    ApplicationCenter.Model.CurrentUser GetCurrentUserWithHashCode(string hascode, string applicationcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetUserListByID", ReplyAction = "http://tempuri.org/IApplicationService/GetUserListByIDResponse")]
    ApplicationCenter.Model.User[] GetUserListByID(string userid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetUserListByIDs", ReplyAction = "http://tempuri.org/IApplicationService/GetUserListByIDsResponse")]
    ApplicationCenter.Model.User[] GetUserListByIDs(string[] userids);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationBaseUrl", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationBaseUrlResponse")]
    string GetApplicationBaseUrl(string appcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GenerateTicket", ReplyAction = "http://tempuri.org/IApplicationService/GenerateTicketResponse")]
    ApplicationCenter.Model.TicketStore GenerateTicket(string userid, string tickettype);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/VerifyTicket", ReplyAction = "http://tempuri.org/IApplicationService/VerifyTicketResponse")]
    bool VerifyTicket(string ticket);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GenerateSMS", ReplyAction = "http://tempuri.org/IApplicationService/GenerateSMSResponse")]
    ApplicationCenter.Model.SMSStore GenerateSMS(string userid, string smstype, string smscode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/SendSMS", ReplyAction = "http://tempuri.org/IApplicationService/SendSMSResponse")]
    ApplicationCenter.Model.SMSStore SendSMS(string smsid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/VerifySMS", ReplyAction = "http://tempuri.org/IApplicationService/VerifySMSResponse")]
    bool VerifySMS(string smscode, string smsid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/Get2FactorCookieExpirationTimeSpan", ReplyAction = "http://tempuri.org/IApplicationService/Get2FactorCookieExpirationTimeSpanResponse" +
        "")]
    double Get2FactorCookieExpirationTimeSpan(string appcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/UserAuthenticationWithAppCodeAndReturnHash" +
        "Code", ReplyAction = "http://tempuri.org/IApplicationService/UserAuthenticationWithAppCodeAndReturnHash" +
        "CodeResponse")]
    string UserAuthenticationWithAppCodeAndReturnHashCode(string userloginaccount, string password, string appcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/UserAuthenticationWithAppCodeDeviceIDAndRe" +
        "turnHashCode", ReplyAction = "http://tempuri.org/IApplicationService/UserAuthenticationWithAppCodeDeviceIDAndRe" +
        "turnHashCodeResponse")]
    string UserAuthenticationWithAppCodeDeviceIDAndReturnHashCode(string userloginaccount, string password, string appcode, string deviceID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/UserAuthenticationWithAppCodeForMobile", ReplyAction = "http://tempuri.org/IApplicationService/UserAuthenticationWithAppCodeForMobileResp" +
        "onse")]
    string UserAuthenticationWithAppCodeForMobile(string userloginaccount, string password, string appcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GenerateServiceTicket", ReplyAction = "http://tempuri.org/IApplicationService/GenerateServiceTicketResponse")]
    string GenerateServiceTicket(string userid, string appcode, ApplicationCenter.Model.AppCenterKeyValuePair[] ticketinfoes);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/VerifyServiceTicket", ReplyAction = "http://tempuri.org/IApplicationService/VerifyServiceTicketResponse")]
    ApplicationCenter.Model.CurrentUser VerifyServiceTicket(string serviceticket);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GenerateEncryptServiceTicket", ReplyAction = "http://tempuri.org/IApplicationService/GenerateEncryptServiceTicketResponse")]
    string GenerateEncryptServiceTicket(string key, string userid, string appcode, ApplicationCenter.Model.AppCenterKeyValuePair[] ticketinfoes);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/VerifyEncryptServiceTicket", ReplyAction = "http://tempuri.org/IApplicationService/VerifyEncryptServiceTicketResponse")]
    string VerifyEncryptServiceTicket(string serviceticket);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/VerifyHashCode", ReplyAction = "http://tempuri.org/IApplicationService/VerifyHashCodeResponse")]
    ApplicationCenter.Model.CurrentUser VerifyHashCode(string hashcode, string applicationcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/VerifyHashCodeReturnSSOTokenUser", ReplyAction = "http://tempuri.org/IApplicationService/VerifyHashCodeReturnSSOTokenUserResponse")]
    ApplicationCenter.Model.SSOTokenUser VerifyHashCodeReturnSSOTokenUser(string hashcode, string applicationcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/VerifyExternalAuthenTicket", ReplyAction = "http://tempuri.org/IApplicationService/VerifyExternalAuthenTicketResponse")]
    ApplicationCenter.Model.CurrentUser VerifyExternalAuthenTicket(string externalAuthenTicket);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GenerateExternalAuthenTicket", ReplyAction = "http://tempuri.org/IApplicationService/GenerateExternalAuthenTicketResponse")]
    string GenerateExternalAuthenTicket(string userid, string externalAutenType, string appcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetMenuRoleMapping", ReplyAction = "http://tempuri.org/IApplicationService/GetMenuRoleMappingResponse")]
    ApplicationCenter.Model.vwMenuRole[] GetMenuRoleMapping(string appcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/VerifySelfDecryptString", ReplyAction = "http://tempuri.org/IApplicationService/VerifySelfDecryptStringResponse")]
    bool VerifySelfDecryptString(string selfdecryptstr, System.TimeSpan timespan);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetSelfDecryptPlainString", ReplyAction = "http://tempuri.org/IApplicationService/GetSelfDecryptPlainStringResponse")]
    string GetSelfDecryptPlainString(string selfdecryptstr);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/VerifyExternalLoginID", ReplyAction = "http://tempuri.org/IApplicationService/VerifyExternalLoginIDResponse")]
    ApplicationCenter.Model.CurrentUser VerifyExternalLoginID(string externalLoginID, string externalLoginInfo, string loginType, string applicationcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/AddExternalLoginForInternalUser", ReplyAction = "http://tempuri.org/IApplicationService/AddExternalLoginForInternalUserResponse")]
    ApplicationCenter.Model.CurrentUser AddExternalLoginForInternalUser(string loginid, string password, string methodcode, string externalLoginID, string externalLoginInfo, string loginType);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetApplicationRoles", ReplyAction = "http://tempuri.org/IApplicationService/GetApplicationRolesResponse")]
    ApplicationCenter.Model.ApplicationRole[] GetApplicationRoles(string applicationcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/AddRole", ReplyAction = "http://tempuri.org/IApplicationService/AddRoleResponse")]
    int AddRole(string roleName, string roleDesc, string roleType, string createdBy, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/AddUser2Role", ReplyAction = "http://tempuri.org/IApplicationService/AddUser2RoleResponse")]
    int AddUser2Role(string roleName, string userID, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/RemoveUserFromRole", ReplyAction = "http://tempuri.org/IApplicationService/RemoveUserFromRoleResponse")]
    int RemoveUserFromRole(string roleName, string userID, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/AddGroup2Role", ReplyAction = "http://tempuri.org/IApplicationService/AddGroup2RoleResponse")]
    int AddGroup2Role(string roleName, string groupName, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/RemoveGroupFromRole", ReplyAction = "http://tempuri.org/IApplicationService/RemoveGroupFromRoleResponse")]
    int RemoveGroupFromRole(string roleName, string groupName, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetUserOfRole", ReplyAction = "http://tempuri.org/IApplicationService/GetUserOfRoleResponse")]
    ApplicationCenter.Model.User[] GetUserOfRole(string roleName, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetGroupOfRole", ReplyAction = "http://tempuri.org/IApplicationService/GetGroupOfRoleResponse")]
    string[] GetGroupOfRole(string roleName, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetUserListByGroupID", ReplyAction = "http://tempuri.org/IApplicationService/GetUserListByGroupIDResponse")]
    ApplicationCenter.Model.User[] GetUserListByGroupID(int groupid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetUserListByGroupName", ReplyAction = "http://tempuri.org/IApplicationService/GetUserListByGroupNameResponse")]
    ApplicationCenter.Model.User[] GetUserListByGroupName(string groupname);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/RemoveGroupFromRoleByIDs", ReplyAction = "http://tempuri.org/IApplicationService/RemoveGroupFromRoleByIDsResponse")]
    int RemoveGroupFromRoleByIDs(System.Guid roleid, int groupid, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/RemoveUserFromRoleByIDs", ReplyAction = "http://tempuri.org/IApplicationService/RemoveUserFromRoleByIDsResponse")]
    int RemoveUserFromRoleByIDs(System.Guid roleid, string userID, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetUserListByRoleNameAndAppCode", ReplyAction = "http://tempuri.org/IApplicationService/GetUserListByRoleNameAndAppCodeResponse")]
    ApplicationCenter.Model.User[] GetUserListByRoleNameAndAppCode(string rolename, string appcode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetUserOfRoleByRoleIDAndAppCode", ReplyAction = "http://tempuri.org/IApplicationService/GetUserOfRoleByRoleIDAndAppCodeResponse")]
    ApplicationCenter.Model.User[] GetUserOfRoleByRoleIDAndAppCode(System.Guid roleid, string appCode);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApplicationService/GetGroupOfRoleByRoleIDAndAppCode", ReplyAction = "http://tempuri.org/IApplicationService/GetGroupOfRoleByRoleIDAndAppCodeResponse")]
    string[] GetGroupOfRoleByRoleIDAndAppCode(System.Guid roleid, string appCode);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
internal interface IApplicationServiceChannel : IApplicationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
internal partial class ApplicationServiceClient : System.ServiceModel.ClientBase<IApplicationService>, IApplicationService
{
    static WcfSetting wcfSettings = WcfSettings.Instance.GetWcfSetting("ApplicationCenter");
    public ApplicationServiceClient() : this(wcfSettings.Binding, wcfSettings.Endpoint)
    {
    }

    public ApplicationServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public ApplicationServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public ApplicationCenter.Model.Application[] GetAllApplicationList()
    {
        return base.Channel.GetAllApplicationList();
    }

    public ApplicationCenter.Model.Application[] GetApplicationList(string userid)
    {
        return base.Channel.GetApplicationList(userid);
    }

    public ApplicationCenter.Model.Application[] GetUserAllApplicationList(string userid)
    {
        return base.Channel.GetUserAllApplicationList(userid);
    }

    public ApplicationCenter.Model.ApplicationRole[] GetApplicationRoleListByCode(string applicationcode)
    {
        return base.Channel.GetApplicationRoleListByCode(applicationcode);
    }

    public ApplicationCenter.Model.ApplicationRole[] GetApplicationRoleListByID(System.Guid applicationid)
    {
        return base.Channel.GetApplicationRoleListByID(applicationid);
    }

    public ApplicationCenter.Model.ApplicationRole[] GetApplicationRoleByCodeAndMenuID(string applicationcode, System.Guid menuid)
    {
        return base.Channel.GetApplicationRoleByCodeAndMenuID(applicationcode, menuid);
    }

    public ApplicationCenter.Model.ApplicationMenu[] GetApplicationMenuByCode(string applicationcode)
    {
        return base.Channel.GetApplicationMenuByCode(applicationcode);
    }

    public ApplicationCenter.Model.ApplicationMenu[] GetApplicationMenuByID(System.Guid applicationid)
    {
        return base.Channel.GetApplicationMenuByID(applicationid);
    }

    public ApplicationCenter.Model.User[] GetUserListByRoleID(System.Guid roleid)
    {
        return base.Channel.GetUserListByRoleID(roleid);
    }

    public ApplicationCenter.Model.ApplicationAuthenticationMethod GetApplicationAuthMethodByID(System.Guid applicationid)
    {
        return base.Channel.GetApplicationAuthMethodByID(applicationid);
    }

    public ApplicationCenter.Model.ApplicationAuthenticationMethod GetApplicationAuthMethodByCode(string applicationcode)
    {
        return base.Channel.GetApplicationAuthMethodByCode(applicationcode);
    }

    public ApplicationCenter.Model.ApplicationAuthenticationMethodWebLogin GetApplicaitonAuthenticationMethodWebLogin(int appauthmethodid)
    {
        return base.Channel.GetApplicaitonAuthenticationMethodWebLogin(appauthmethodid);
    }

    public string UserAuthentication(string userloginaccount, string password, string authenticationmethod)
    {
        return base.Channel.UserAuthentication(userloginaccount, password, authenticationmethod);
    }

    public string UserAuthenticationWithAppCode(string userloginaccount, string password, string appcode)
    {
        return base.Channel.UserAuthenticationWithAppCode(userloginaccount, password, appcode);
    }

    public bool TwoFactorsAuthentication(string userid, string twofactorscode, string authenticationmethod)
    {
        return base.Channel.TwoFactorsAuthentication(userid, twofactorscode, authenticationmethod);
    }

    public ApplicationCenter.Model.CurrentUser GetCurrentUser(string userid, string applicationcode)
    {
        return base.Channel.GetCurrentUser(userid, applicationcode);
    }

    public ApplicationCenter.Model.CurrentUser GetCurrentUserWithHashCode(string hascode, string applicationcode)
    {
        return base.Channel.GetCurrentUserWithHashCode(hascode, applicationcode);
    }

    public ApplicationCenter.Model.User[] GetUserListByID(string userid)
    {
        return base.Channel.GetUserListByID(userid);
    }

    public ApplicationCenter.Model.User[] GetUserListByIDs(string[] userids)
    {
        return base.Channel.GetUserListByIDs(userids);
    }

    public string GetApplicationBaseUrl(string appcode)
    {
        return base.Channel.GetApplicationBaseUrl(appcode);
    }

    public ApplicationCenter.Model.TicketStore GenerateTicket(string userid, string tickettype)
    {
        return base.Channel.GenerateTicket(userid, tickettype);
    }

    public bool VerifyTicket(string ticket)
    {
        return base.Channel.VerifyTicket(ticket);
    }

    public ApplicationCenter.Model.SMSStore GenerateSMS(string userid, string smstype, string smscode)
    {
        return base.Channel.GenerateSMS(userid, smstype, smscode);
    }

    public ApplicationCenter.Model.SMSStore SendSMS(string smsid)
    {
        return base.Channel.SendSMS(smsid);
    }

    public bool VerifySMS(string smscode, string smsid)
    {
        return base.Channel.VerifySMS(smscode, smsid);
    }

    public double Get2FactorCookieExpirationTimeSpan(string appcode)
    {
        return base.Channel.Get2FactorCookieExpirationTimeSpan(appcode);
    }

    public string UserAuthenticationWithAppCodeAndReturnHashCode(string userloginaccount, string password, string appcode)
    {
        return base.Channel.UserAuthenticationWithAppCodeAndReturnHashCode(userloginaccount, password, appcode);
    }

    public string UserAuthenticationWithAppCodeDeviceIDAndReturnHashCode(string userloginaccount, string password, string appcode, string deviceID)
    {
        return base.Channel.UserAuthenticationWithAppCodeDeviceIDAndReturnHashCode(userloginaccount, password, appcode, deviceID);
    }

    public string UserAuthenticationWithAppCodeForMobile(string userloginaccount, string password, string appcode)
    {
        return base.Channel.UserAuthenticationWithAppCodeForMobile(userloginaccount, password, appcode);
    }

    public string GenerateServiceTicket(string userid, string appcode, ApplicationCenter.Model.AppCenterKeyValuePair[] ticketinfoes)
    {
        return base.Channel.GenerateServiceTicket(userid, appcode, ticketinfoes);
    }

    public ApplicationCenter.Model.CurrentUser VerifyServiceTicket(string serviceticket)
    {
        return base.Channel.VerifyServiceTicket(serviceticket);
    }

    public string GenerateEncryptServiceTicket(string key, string userid, string appcode, ApplicationCenter.Model.AppCenterKeyValuePair[] ticketinfoes)
    {
        return base.Channel.GenerateEncryptServiceTicket(key, userid, appcode, ticketinfoes);
    }

    public string VerifyEncryptServiceTicket(string serviceticket)
    {
        return base.Channel.VerifyEncryptServiceTicket(serviceticket);
    }

    public ApplicationCenter.Model.CurrentUser VerifyHashCode(string hashcode, string applicationcode)
    {
        return base.Channel.VerifyHashCode(hashcode, applicationcode);
    }

    public ApplicationCenter.Model.SSOTokenUser VerifyHashCodeReturnSSOTokenUser(string hashcode, string applicationcode)
    {
        return base.Channel.VerifyHashCodeReturnSSOTokenUser(hashcode, applicationcode);
    }

    public ApplicationCenter.Model.CurrentUser VerifyExternalAuthenTicket(string externalAuthenTicket)
    {
        return base.Channel.VerifyExternalAuthenTicket(externalAuthenTicket);
    }

    public string GenerateExternalAuthenTicket(string userid, string externalAutenType, string appcode)
    {
        return base.Channel.GenerateExternalAuthenTicket(userid, externalAutenType, appcode);
    }

    public ApplicationCenter.Model.vwMenuRole[] GetMenuRoleMapping(string appcode)
    {
        return base.Channel.GetMenuRoleMapping(appcode);
    }

    public bool VerifySelfDecryptString(string selfdecryptstr, System.TimeSpan timespan)
    {
        return base.Channel.VerifySelfDecryptString(selfdecryptstr, timespan);
    }

    public string GetSelfDecryptPlainString(string selfdecryptstr)
    {
        return base.Channel.GetSelfDecryptPlainString(selfdecryptstr);
    }

    public ApplicationCenter.Model.CurrentUser VerifyExternalLoginID(string externalLoginID, string externalLoginInfo, string loginType, string applicationcode)
    {
        return base.Channel.VerifyExternalLoginID(externalLoginID, externalLoginInfo, loginType, applicationcode);
    }

    public ApplicationCenter.Model.CurrentUser AddExternalLoginForInternalUser(string loginid, string password, string methodcode, string externalLoginID, string externalLoginInfo, string loginType)
    {
        return base.Channel.AddExternalLoginForInternalUser(loginid, password, methodcode, externalLoginID, externalLoginInfo, loginType);
    }

    public ApplicationCenter.Model.ApplicationRole[] GetApplicationRoles(string applicationcode)
    {
        return base.Channel.GetApplicationRoles(applicationcode);
    }

    public int AddRole(string roleName, string roleDesc, string roleType, string createdBy, string appCode)
    {
        return base.Channel.AddRole(roleName, roleDesc, roleType, createdBy, appCode);
    }

    public int AddUser2Role(string roleName, string userID, string appCode)
    {
        return base.Channel.AddUser2Role(roleName, userID, appCode);
    }

    public int RemoveUserFromRole(string roleName, string userID, string appCode)
    {
        return base.Channel.RemoveUserFromRole(roleName, userID, appCode);
    }

    public int AddGroup2Role(string roleName, string groupName, string appCode)
    {
        return base.Channel.AddGroup2Role(roleName, groupName, appCode);
    }

    public int RemoveGroupFromRole(string roleName, string groupName, string appCode)
    {
        return base.Channel.RemoveGroupFromRole(roleName, groupName, appCode);
    }

    public ApplicationCenter.Model.User[] GetUserOfRole(string roleName, string appCode)
    {
        return base.Channel.GetUserOfRole(roleName, appCode);
    }

    public string[] GetGroupOfRole(string roleName, string appCode)
    {
        return base.Channel.GetGroupOfRole(roleName, appCode);
    }

    public ApplicationCenter.Model.User[] GetUserListByGroupID(int groupid)
    {
        return base.Channel.GetUserListByGroupID(groupid);
    }

    public ApplicationCenter.Model.User[] GetUserListByGroupName(string groupname)
    {
        return base.Channel.GetUserListByGroupName(groupname);
    }

    public int RemoveGroupFromRoleByIDs(System.Guid roleid, int groupid, string appCode)
    {
        return base.Channel.RemoveGroupFromRoleByIDs(roleid, groupid, appCode);
    }

    public int RemoveUserFromRoleByIDs(System.Guid roleid, string userID, string appCode)
    {
        return base.Channel.RemoveUserFromRoleByIDs(roleid, userID, appCode);
    }

    public ApplicationCenter.Model.User[] GetUserListByRoleNameAndAppCode(string rolename, string appcode)
    {
        return base.Channel.GetUserListByRoleNameAndAppCode(rolename, appcode);
    }

    public ApplicationCenter.Model.User[] GetUserOfRoleByRoleIDAndAppCode(System.Guid roleid, string appCode)
    {
        return base.Channel.GetUserOfRoleByRoleIDAndAppCode(roleid, appCode);
    }

    public string[] GetGroupOfRoleByRoleIDAndAppCode(System.Guid roleid, string appCode)
    {
        return base.Channel.GetGroupOfRoleByRoleIDAndAppCode(roleid, appCode);
    }
}
