//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PwC.C4.Configuration.WcfSettings;

namespace PwC.C4.DataService.Model
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EmailParameter", Namespace = "http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class EmailParameter : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AppCodeField;

        private string AssemblyField;

        private string ContentField;

        private string CreateByField;

        private System.DateTime CreateDateField;

        private string GroupField;

        private bool IsDeletedField;

        private string ModifyByField;

        private System.DateTime ModifyDateField;

        private string ParameterCodeField;

        private int ParameterIdField;

        private string ParameterNameField;

        private PwC.C4.DataService.Model.Enum.ParameterType ParameterTypeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assembly
        {
            get
            {
                return this.AssemblyField;
            }
            set
            {
                this.AssemblyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyBy
        {
            get
            {
                return this.ModifyByField;
            }
            set
            {
                this.ModifyByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate
        {
            get
            {
                return this.ModifyDateField;
            }
            set
            {
                this.ModifyDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterCode
        {
            get
            {
                return this.ParameterCodeField;
            }
            set
            {
                this.ParameterCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParameterId
        {
            get
            {
                return this.ParameterIdField;
            }
            set
            {
                this.ParameterIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterName
        {
            get
            {
                return this.ParameterNameField;
            }
            set
            {
                this.ParameterNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PwC.C4.DataService.Model.Enum.ParameterType ParameterType
        {
            get
            {
                return this.ParameterTypeField;
            }
            set
            {
                this.ParameterTypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EmailTemplate", Namespace = "http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class EmailTemplate : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AppCodeField;

        private string CreateByField;

        private System.DateTime CreateDateField;

        private string GroupField;

        private bool IsDeletedField;

        private bool IsImmediateField;

        private string MailBccField;

        private string MailCcField;

        private string MailContentField;

        private string MailFromField;

        private string MailOrganisationField;

        private string MailReplyToField;

        private string MailSubjectField;

        private string MailSubmitByField;

        private string ModifyByField;

        private System.DateTime ModifyDateField;

        private string TemplateCodeField;

        private int TemplateIdField;

        private string TemplateNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsImmediate
        {
            get
            {
                return this.IsImmediateField;
            }
            set
            {
                this.IsImmediateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailBcc
        {
            get
            {
                return this.MailBccField;
            }
            set
            {
                this.MailBccField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCc
        {
            get
            {
                return this.MailCcField;
            }
            set
            {
                this.MailCcField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailContent
        {
            get
            {
                return this.MailContentField;
            }
            set
            {
                this.MailContentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailFrom
        {
            get
            {
                return this.MailFromField;
            }
            set
            {
                this.MailFromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailOrganisation
        {
            get
            {
                return this.MailOrganisationField;
            }
            set
            {
                this.MailOrganisationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailReplyTo
        {
            get
            {
                return this.MailReplyToField;
            }
            set
            {
                this.MailReplyToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailSubject
        {
            get
            {
                return this.MailSubjectField;
            }
            set
            {
                this.MailSubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailSubmitBy
        {
            get
            {
                return this.MailSubmitByField;
            }
            set
            {
                this.MailSubmitByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyBy
        {
            get
            {
                return this.ModifyByField;
            }
            set
            {
                this.ModifyByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate
        {
            get
            {
                return this.ModifyDateField;
            }
            set
            {
                this.ModifyDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateCode
        {
            get
            {
                return this.TemplateCodeField;
            }
            set
            {
                this.TemplateCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateId
        {
            get
            {
                return this.TemplateIdField;
            }
            set
            {
                this.TemplateIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName
        {
            get
            {
                return this.TemplateNameField;
            }
            set
            {
                this.TemplateNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MailQueueModel", Namespace = "http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class MailQueueModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AppCodeField;

        private string ContentField;

        private string ImmediateFlagField;

        private string MailBccField;

        private string MailCcField;

        private string MailFromField;

        private string MailToField;

        private string OrganisationField;

        private string ReplyToField;

        private System.DateTime SendDateField;

        private string SendFromField;

        private string SubjectField;

        private string SubmitByField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImmediateFlag
        {
            get
            {
                return this.ImmediateFlagField;
            }
            set
            {
                this.ImmediateFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailBcc
        {
            get
            {
                return this.MailBccField;
            }
            set
            {
                this.MailBccField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCc
        {
            get
            {
                return this.MailCcField;
            }
            set
            {
                this.MailCcField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailFrom
        {
            get
            {
                return this.MailFromField;
            }
            set
            {
                this.MailFromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailTo
        {
            get
            {
                return this.MailToField;
            }
            set
            {
                this.MailToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organisation
        {
            get
            {
                return this.OrganisationField;
            }
            set
            {
                this.OrganisationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplyTo
        {
            get
            {
                return this.ReplyToField;
            }
            set
            {
                this.ReplyToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendFrom
        {
            get
            {
                return this.SendFromField;
            }
            set
            {
                this.SendFromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitBy
        {
            get
            {
                return this.SubmitByField;
            }
            set
            {
                this.SubmitByField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MailAttachment", Namespace = "http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class MailAttachment : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private byte[] ContentField;

        private string FileNameField;

        private bool LinkedResourceFlagField;

        private string MimeTypeField;

        private string NameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LinkedResourceFlag
        {
            get
            {
                return this.LinkedResourceFlagField;
            }
            set
            {
                this.LinkedResourceFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WorkflowBase", Namespace = "http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class WorkflowBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ActionCodeField;

        private string AppCodeField;

        private string CommentField;

        private System.DateTime CreateTimeField;

        private string EntityNameField;

        private int FormIdField;

        private int IdField;

        private int InstanceIdField;

        private bool IsActiveField;

        private string RecordIdField;

        private string StatusField;

        private string UserIdField;

        private string UserRoleField;

        private string WorkflowCodeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode
        {
            get
            {
                return this.ActionCodeField;
            }
            set
            {
                this.ActionCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityName
        {
            get
            {
                return this.EntityNameField;
            }
            set
            {
                this.EntityNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormId
        {
            get
            {
                return this.FormIdField;
            }
            set
            {
                this.FormIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstanceId
        {
            get
            {
                return this.InstanceIdField;
            }
            set
            {
                this.InstanceIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecordId
        {
            get
            {
                return this.RecordIdField;
            }
            set
            {
                this.RecordIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRole
        {
            get
            {
                return this.UserRoleField;
            }
            set
            {
                this.UserRoleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkflowCode
        {
            get
            {
                return this.WorkflowCodeField;
            }
            set
            {
                this.WorkflowCodeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "StaffInfo", Namespace = "http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class StaffInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string BUField;

        private string BUDescField;

        private string ChineseNameField;

        private string CityField;

        private System.Nullable<System.DateTime> ContractYearEndField;

        private string CountryCodeField;

        private string CountryOfficeField;

        private string DepartmentField;

        private string DivCodeField;

        private string DivNameField;

        private string EmailField;

        private string EmployeeCategoryField;

        private string ExpatFlagField;

        private string FirstNameField;

        private string FullNameField;

        private string GUIDField;

        private string GivenNameField;

        private string GradeCodeField;

        private string GradeNameField;

        private string GroupCodeField;

        private string GroupNameField;

        private string HRIDField;

        private string IDTerritoryField;

        private string INetEmailField;

        private string IsProfessionalField;

        private string JobCodeField;

        private string JobGradeField;

        private string JobTitleField;

        private System.Nullable<System.DateTime> JoinDateField;

        private string LDAP_DistNameField;

        private string LastNameField;

        private string LoSField;

        private string LoSDescField;

        private string LoginContextField;

        private string LoginIDField;

        private string MajorityField;

        private string MajorityCategoryField;

        private string NameInEngField;

        private string NativeNameField;

        private string NotesIDField;

        private string OUCodeField;

        private string OfficeBuildingField;

        private string OfficeCityNameField;

        private string OfficeFloorField;

        private string OfficePINField;

        private string PhoneNoField;

        private byte[] PicField;

        private string PicTypeField;

        private string PowerGradeCodeField;

        private string PowerGroupCodeField;

        private string PowerIDStatusField;

        private string PowerStaffCodeField;

        private string PreferredNameField;

        private string PwCEntityIDField;

        private string RoleField;

        private string SalaryCategoryField;

        private string SchoolUniversityField;

        private string SecNameField;

        private string SexField;

        private string StaffIdField;

        private string StaffInitialField;

        private string StaffNameField;

        private string StatusField;

        private string SubServiceField;

        private string SubServiceDescField;

        private System.Nullable<System.DateTime> TermDateField;

        private string TermFlagField;

        private System.Nullable<System.DateTime> TerritoryEffectiveDateField;

        private string localExpatFlagField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BU
        {
            get
            {
                return this.BUField;
            }
            set
            {
                this.BUField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BUDesc
        {
            get
            {
                return this.BUDescField;
            }
            set
            {
                this.BUDescField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChineseName
        {
            get
            {
                return this.ChineseNameField;
            }
            set
            {
                this.ChineseNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ContractYearEnd
        {
            get
            {
                return this.ContractYearEndField;
            }
            set
            {
                this.ContractYearEndField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryOffice
        {
            get
            {
                return this.CountryOfficeField;
            }
            set
            {
                this.CountryOfficeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivCode
        {
            get
            {
                return this.DivCodeField;
            }
            set
            {
                this.DivCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivName
        {
            get
            {
                return this.DivNameField;
            }
            set
            {
                this.DivNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeCategory
        {
            get
            {
                return this.EmployeeCategoryField;
            }
            set
            {
                this.EmployeeCategoryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpatFlag
        {
            get
            {
                return this.ExpatFlagField;
            }
            set
            {
                this.ExpatFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUID
        {
            get
            {
                return this.GUIDField;
            }
            set
            {
                this.GUIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GivenName
        {
            get
            {
                return this.GivenNameField;
            }
            set
            {
                this.GivenNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeCode
        {
            get
            {
                return this.GradeCodeField;
            }
            set
            {
                this.GradeCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeName
        {
            get
            {
                return this.GradeNameField;
            }
            set
            {
                this.GradeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupCode
        {
            get
            {
                return this.GroupCodeField;
            }
            set
            {
                this.GroupCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HRID
        {
            get
            {
                return this.HRIDField;
            }
            set
            {
                this.HRIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDTerritory
        {
            get
            {
                return this.IDTerritoryField;
            }
            set
            {
                this.IDTerritoryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INetEmail
        {
            get
            {
                return this.INetEmailField;
            }
            set
            {
                this.INetEmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsProfessional
        {
            get
            {
                return this.IsProfessionalField;
            }
            set
            {
                this.IsProfessionalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobCode
        {
            get
            {
                return this.JobCodeField;
            }
            set
            {
                this.JobCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobGrade
        {
            get
            {
                return this.JobGradeField;
            }
            set
            {
                this.JobGradeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle
        {
            get
            {
                return this.JobTitleField;
            }
            set
            {
                this.JobTitleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> JoinDate
        {
            get
            {
                return this.JoinDateField;
            }
            set
            {
                this.JoinDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LDAP_DistName
        {
            get
            {
                return this.LDAP_DistNameField;
            }
            set
            {
                this.LDAP_DistNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoS
        {
            get
            {
                return this.LoSField;
            }
            set
            {
                this.LoSField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoSDesc
        {
            get
            {
                return this.LoSDescField;
            }
            set
            {
                this.LoSDescField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginContext
        {
            get
            {
                return this.LoginContextField;
            }
            set
            {
                this.LoginContextField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginID
        {
            get
            {
                return this.LoginIDField;
            }
            set
            {
                this.LoginIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Majority
        {
            get
            {
                return this.MajorityField;
            }
            set
            {
                this.MajorityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorityCategory
        {
            get
            {
                return this.MajorityCategoryField;
            }
            set
            {
                this.MajorityCategoryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameInEng
        {
            get
            {
                return this.NameInEngField;
            }
            set
            {
                this.NameInEngField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NativeName
        {
            get
            {
                return this.NativeNameField;
            }
            set
            {
                this.NativeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotesID
        {
            get
            {
                return this.NotesIDField;
            }
            set
            {
                this.NotesIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OUCode
        {
            get
            {
                return this.OUCodeField;
            }
            set
            {
                this.OUCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeBuilding
        {
            get
            {
                return this.OfficeBuildingField;
            }
            set
            {
                this.OfficeBuildingField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeCityName
        {
            get
            {
                return this.OfficeCityNameField;
            }
            set
            {
                this.OfficeCityNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeFloor
        {
            get
            {
                return this.OfficeFloorField;
            }
            set
            {
                this.OfficeFloorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficePIN
        {
            get
            {
                return this.OfficePINField;
            }
            set
            {
                this.OfficePINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo
        {
            get
            {
                return this.PhoneNoField;
            }
            set
            {
                this.PhoneNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Pic
        {
            get
            {
                return this.PicField;
            }
            set
            {
                this.PicField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PicType
        {
            get
            {
                return this.PicTypeField;
            }
            set
            {
                this.PicTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerGradeCode
        {
            get
            {
                return this.PowerGradeCodeField;
            }
            set
            {
                this.PowerGradeCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerGroupCode
        {
            get
            {
                return this.PowerGroupCodeField;
            }
            set
            {
                this.PowerGroupCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerIDStatus
        {
            get
            {
                return this.PowerIDStatusField;
            }
            set
            {
                this.PowerIDStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerStaffCode
        {
            get
            {
                return this.PowerStaffCodeField;
            }
            set
            {
                this.PowerStaffCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredName
        {
            get
            {
                return this.PreferredNameField;
            }
            set
            {
                this.PreferredNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PwCEntityID
        {
            get
            {
                return this.PwCEntityIDField;
            }
            set
            {
                this.PwCEntityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalaryCategory
        {
            get
            {
                return this.SalaryCategoryField;
            }
            set
            {
                this.SalaryCategoryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolUniversity
        {
            get
            {
                return this.SchoolUniversityField;
            }
            set
            {
                this.SchoolUniversityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecName
        {
            get
            {
                return this.SecNameField;
            }
            set
            {
                this.SecNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffId
        {
            get
            {
                return this.StaffIdField;
            }
            set
            {
                this.StaffIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffInitial
        {
            get
            {
                return this.StaffInitialField;
            }
            set
            {
                this.StaffInitialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffName
        {
            get
            {
                return this.StaffNameField;
            }
            set
            {
                this.StaffNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubService
        {
            get
            {
                return this.SubServiceField;
            }
            set
            {
                this.SubServiceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubServiceDesc
        {
            get
            {
                return this.SubServiceDescField;
            }
            set
            {
                this.SubServiceDescField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TermDate
        {
            get
            {
                return this.TermDateField;
            }
            set
            {
                this.TermDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TermFlag
        {
            get
            {
                return this.TermFlagField;
            }
            set
            {
                this.TermFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TerritoryEffectiveDate
        {
            get
            {
                return this.TerritoryEffectiveDateField;
            }
            set
            {
                this.TerritoryEffectiveDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localExpatFlag
        {
            get
            {
                return this.localExpatFlagField;
            }
            set
            {
                this.localExpatFlagField = value;
            }
        }
    }
}
namespace PwC.C4.DataService.Model.Enum
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ParameterType", Namespace = "http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model.Enum")]
    public enum ParameterType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Interface = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Razor = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mapping = 4,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IC4CommonService")]
public interface IC4CommonService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameter_Create", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameter_CreateResponse")]
    int EmailParameter_Create(PwC.C4.DataService.Model.EmailParameter model);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameter_Create", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameter_CreateResponse")]
    System.Threading.Tasks.Task<int> EmailParameter_CreateAsync(PwC.C4.DataService.Model.EmailParameter model);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameter_Get", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameter_GetResponse")]
    PwC.C4.DataService.Model.EmailParameter EmailParameter_Get(string appcode, int paraId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameter_Get", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameter_GetResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.EmailParameter> EmailParameter_GetAsync(string appcode, int paraId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameters_GetByGroup", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameters_GetByGroupResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter> EmailParameters_GetByGroup(string appcode, string groupName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameters_GetByGroup", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameters_GetByGroupResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter>> EmailParameters_GetByGroupAsync(string appcode, string groupName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameters_GetByPaging", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameters_GetByPagingResponse")]
    EmailParameters_GetByPagingResponse EmailParameters_GetByPaging(EmailParameters_GetByPagingRequest request);

    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameters_GetByPaging", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameters_GetByPagingResponse")]
    System.Threading.Tasks.Task<EmailParameters_GetByPagingResponse> EmailParameters_GetByPagingAsync(EmailParameters_GetByPagingRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameters_GetByCodes", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameters_GetByCodesResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter> EmailParameters_GetByCodes(string appcode, System.Collections.Generic.List<string> codes, string groupName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameters_GetByCodes", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameters_GetByCodesResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter>> EmailParameters_GetByCodesAsync(string appcode, System.Collections.Generic.List<string> codes, string groupName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameter_Update", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameter_UpdateResponse")]
    int EmailParameter_Update(PwC.C4.DataService.Model.EmailParameter emailParameter);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameter_Update", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameter_UpdateResponse")]
    System.Threading.Tasks.Task<int> EmailParameter_UpdateAsync(PwC.C4.DataService.Model.EmailParameter emailParameter);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameter_Delete", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameter_DeleteResponse")]
    bool EmailParameter_Delete(string appcode, int paraId, int modifyBy);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailParameter_Delete", ReplyAction = "http://tempuri.org/IC4CommonService/EmailParameter_DeleteResponse")]
    System.Threading.Tasks.Task<bool> EmailParameter_DeleteAsync(string appcode, int paraId, int modifyBy);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplate_Create", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplate_CreateResponse")]
    int EmailTemplate_Create(PwC.C4.DataService.Model.EmailTemplate model);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplate_Create", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplate_CreateResponse")]
    System.Threading.Tasks.Task<int> EmailTemplate_CreateAsync(PwC.C4.DataService.Model.EmailTemplate model);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplate_Get", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplate_GetResponse")]
    PwC.C4.DataService.Model.EmailTemplate EmailTemplate_Get(string appcode, int tId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplate_Get", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplate_GetResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.EmailTemplate> EmailTemplate_GetAsync(string appcode, int tId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByGroup", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByGroupResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate> EmailTemplates_GetByGroup(string appcode, string groupName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByGroup", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByGroupResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate>> EmailTemplates_GetByGroupAsync(string appcode, string groupName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByPaging", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByPagingResponse")]
    EmailTemplates_GetByPagingResponse EmailTemplates_GetByPaging(EmailTemplates_GetByPagingRequest request);

    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByPaging", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByPagingResponse")]
    System.Threading.Tasks.Task<EmailTemplates_GetByPagingResponse> EmailTemplates_GetByPagingAsync(EmailTemplates_GetByPagingRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByCodes", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByCodesResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate> EmailTemplates_GetByCodes(string appcode, System.Collections.Generic.List<string> codes, string groupName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByCodes", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplates_GetByCodesResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate>> EmailTemplates_GetByCodesAsync(string appcode, System.Collections.Generic.List<string> codes, string groupName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplate_Update", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplate_UpdateResponse")]
    int EmailTemplate_Update(PwC.C4.DataService.Model.EmailTemplate emailTemplate);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplate_Update", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplate_UpdateResponse")]
    System.Threading.Tasks.Task<int> EmailTemplate_UpdateAsync(PwC.C4.DataService.Model.EmailTemplate emailTemplate);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplate_Delete", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplate_DeleteResponse")]
    bool EmailTemplate_Delete(string appcode, int tId, int modifyBy);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/EmailTemplate_Delete", ReplyAction = "http://tempuri.org/IC4CommonService/EmailTemplate_DeleteResponse")]
    System.Threading.Tasks.Task<bool> EmailTemplate_DeleteAsync(string appcode, int tId, int modifyBy);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/InsertToMailQueue", ReplyAction = "http://tempuri.org/IC4CommonService/InsertToMailQueueResponse")]
    int InsertToMailQueue(PwC.C4.DataService.Model.MailQueueModel model);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/InsertToMailQueue", ReplyAction = "http://tempuri.org/IC4CommonService/InsertToMailQueueResponse")]
    System.Threading.Tasks.Task<int> InsertToMailQueueAsync(PwC.C4.DataService.Model.MailQueueModel model);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/InsertToMailQueueWithAttachment", ReplyAction = "http://tempuri.org/IC4CommonService/InsertToMailQueueWithAttachmentResponse")]
    int InsertToMailQueueWithAttachment(PwC.C4.DataService.Model.MailQueueModel model, System.Collections.Generic.List<PwC.C4.DataService.Model.MailAttachment> attachments);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/InsertToMailQueueWithAttachment", ReplyAction = "http://tempuri.org/IC4CommonService/InsertToMailQueueWithAttachmentResponse")]
    System.Threading.Tasks.Task<int> InsertToMailQueueWithAttachmentAsync(PwC.C4.DataService.Model.MailQueueModel model, System.Collections.Generic.List<PwC.C4.DataService.Model.MailAttachment> attachments);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/InsertToMailQueueWithAttachmentId", ReplyAction = "http://tempuri.org/IC4CommonService/InsertToMailQueueWithAttachmentIdResponse")]
    int InsertToMailQueueWithAttachmentId(PwC.C4.DataService.Model.MailQueueModel model, System.Collections.Generic.List<int> attachmentIds);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/InsertToMailQueueWithAttachmentId", ReplyAction = "http://tempuri.org/IC4CommonService/InsertToMailQueueWithAttachmentIdResponse")]
    System.Threading.Tasks.Task<int> InsertToMailQueueWithAttachmentIdAsync(PwC.C4.DataService.Model.MailQueueModel model, System.Collections.Generic.List<int> attachmentIds);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/InsertToMailAttachment", ReplyAction = "http://tempuri.org/IC4CommonService/InsertToMailAttachmentResponse")]
    int InsertToMailAttachment(PwC.C4.DataService.Model.MailAttachment attachment);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/InsertToMailAttachment", ReplyAction = "http://tempuri.org/IC4CommonService/InsertToMailAttachmentResponse")]
    System.Threading.Tasks.Task<int> InsertToMailAttachmentAsync(PwC.C4.DataService.Model.MailAttachment attachment);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetByFormId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetByFormIdResponse")]
    PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetByFormId(string appcode, string entityName, int formId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetByFormId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetByFormIdResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetByFormIdAsync(string appcode, string entityName, int formId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetByRecordId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetByRecordIdResponse")]
    PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetByRecordId(string appcode, string entityName, string recordId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetByRecordId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetByRecordIdResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetByRecordIdAsync(string appcode, string entityName, string recordId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetLastUnactivedByInstanceId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetLastUnactivedByInstanceIdResponse" +
        "")]
    PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetLastUnactivedByInstanceId(string appcode, string workflowCode, int instanceId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetLastUnactivedByInstanceId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetLastUnactivedByInstanceIdResponse" +
        "")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetLastUnactivedByInstanceIdAsync(string appcode, string workflowCode, int instanceId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetLastUnactivedByRecordId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetLastUnactivedByRecordIdResponse")]
    PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetLastUnactivedByRecordId(string appcode, string entityName, string recordId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetLastUnactivedByRecordId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetLastUnactivedByRecordIdResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetLastUnactivedByRecordIdAsync(string appcode, string entityName, string recordId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetActiveByInstanceId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetActiveByInstanceIdResponse")]
    PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetActiveByInstanceId(string appcode, int instanceId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/WorkFlow_GetActiveByInstanceId", ReplyAction = "http://tempuri.org/IC4CommonService/WorkFlow_GetActiveByInstanceIdResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetActiveByInstanceIdAsync(string appcode, int instanceId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/Workflow_Insert", ReplyAction = "http://tempuri.org/IC4CommonService/Workflow_InsertResponse")]
    int Workflow_Insert(PwC.C4.DataService.Model.WorkflowBase model);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/Workflow_Insert", ReplyAction = "http://tempuri.org/IC4CommonService/Workflow_InsertResponse")]
    System.Threading.Tasks.Task<int> Workflow_InsertAsync(PwC.C4.DataService.Model.WorkflowBase model);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/Staff_Get", ReplyAction = "http://tempuri.org/IC4CommonService/Staff_GetResponse")]
    PwC.C4.DataService.Model.StaffInfo Staff_Get(string staffId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/Staff_Get", ReplyAction = "http://tempuri.org/IC4CommonService/Staff_GetResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.StaffInfo> Staff_GetAsync(string staffId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/Staff_GetList", ReplyAction = "http://tempuri.org/IC4CommonService/Staff_GetListResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.StaffInfo> Staff_GetList(string where);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IC4CommonService/Staff_GetList", ReplyAction = "http://tempuri.org/IC4CommonService/Staff_GetListResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.StaffInfo>> Staff_GetListAsync(string where);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "EmailParameters_GetByPaging", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class EmailParameters_GetByPagingRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public string appcode;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    public string name;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    public int pageIndex;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public int pageSize;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    public string groupName;

    public EmailParameters_GetByPagingRequest()
    {
    }

    public EmailParameters_GetByPagingRequest(string appcode, string name, int pageIndex, int pageSize, string groupName)
    {
        this.appcode = appcode;
        this.name = name;
        this.pageIndex = pageIndex;
        this.pageSize = pageSize;
        this.groupName = groupName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "EmailParameters_GetByPagingResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class EmailParameters_GetByPagingResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter> EmailParameters_GetByPagingResult;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    public int totalCount;

    public EmailParameters_GetByPagingResponse()
    {
    }

    public EmailParameters_GetByPagingResponse(System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter> EmailParameters_GetByPagingResult, int totalCount)
    {
        this.EmailParameters_GetByPagingResult = EmailParameters_GetByPagingResult;
        this.totalCount = totalCount;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "EmailTemplates_GetByPaging", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class EmailTemplates_GetByPagingRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public string appcode;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    public string name;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    public int pageIndex;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public int pageSize;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    public string groupName;

    public EmailTemplates_GetByPagingRequest()
    {
    }

    public EmailTemplates_GetByPagingRequest(string appcode, string name, int pageIndex, int pageSize, string groupName)
    {
        this.appcode = appcode;
        this.name = name;
        this.pageIndex = pageIndex;
        this.pageSize = pageSize;
        this.groupName = groupName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "EmailTemplates_GetByPagingResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class EmailTemplates_GetByPagingResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate> EmailTemplates_GetByPagingResult;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    public int totalCount;

    public EmailTemplates_GetByPagingResponse()
    {
    }

    public EmailTemplates_GetByPagingResponse(System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate> EmailTemplates_GetByPagingResult, int totalCount)
    {
        this.EmailTemplates_GetByPagingResult = EmailTemplates_GetByPagingResult;
        this.totalCount = totalCount;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IC4CommonServiceChannel : IC4CommonService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class C4CommonServiceClient : System.ServiceModel.ClientBase<IC4CommonService>, IC4CommonService
{
    static WcfSetting wcfSettings = WcfSettings.Instance.GetWcfSetting("C4CommonService");
    public C4CommonServiceClient() : this(wcfSettings.Binding, wcfSettings.Endpoint)
    {
    }

    public C4CommonServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public C4CommonServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public C4CommonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public C4CommonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public int EmailParameter_Create(PwC.C4.DataService.Model.EmailParameter model)
    {
        return base.Channel.EmailParameter_Create(model);
    }

    public System.Threading.Tasks.Task<int> EmailParameter_CreateAsync(PwC.C4.DataService.Model.EmailParameter model)
    {
        return base.Channel.EmailParameter_CreateAsync(model);
    }

    public PwC.C4.DataService.Model.EmailParameter EmailParameter_Get(string appcode, int paraId)
    {
        return base.Channel.EmailParameter_Get(appcode, paraId);
    }

    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.EmailParameter> EmailParameter_GetAsync(string appcode, int paraId)
    {
        return base.Channel.EmailParameter_GetAsync(appcode, paraId);
    }

    public System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter> EmailParameters_GetByGroup(string appcode, string groupName)
    {
        return base.Channel.EmailParameters_GetByGroup(appcode, groupName);
    }

    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter>> EmailParameters_GetByGroupAsync(string appcode, string groupName)
    {
        return base.Channel.EmailParameters_GetByGroupAsync(appcode, groupName);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    EmailParameters_GetByPagingResponse IC4CommonService.EmailParameters_GetByPaging(EmailParameters_GetByPagingRequest request)
    {
        return base.Channel.EmailParameters_GetByPaging(request);
    }

    public System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter> EmailParameters_GetByPaging(string appcode, string name, int pageIndex, int pageSize, string groupName, out int totalCount)
    {
        EmailParameters_GetByPagingRequest inValue = new EmailParameters_GetByPagingRequest();
        inValue.appcode = appcode;
        inValue.name = name;
        inValue.pageIndex = pageIndex;
        inValue.pageSize = pageSize;
        inValue.groupName = groupName;
        EmailParameters_GetByPagingResponse retVal = ((IC4CommonService)(this)).EmailParameters_GetByPaging(inValue);
        totalCount = retVal.totalCount;
        return retVal.EmailParameters_GetByPagingResult;
    }

    public System.Threading.Tasks.Task<EmailParameters_GetByPagingResponse> EmailParameters_GetByPagingAsync(EmailParameters_GetByPagingRequest request)
    {
        return base.Channel.EmailParameters_GetByPagingAsync(request);
    }

    public System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter> EmailParameters_GetByCodes(string appcode, System.Collections.Generic.List<string> codes, string groupName)
    {
        return base.Channel.EmailParameters_GetByCodes(appcode, codes, groupName);
    }

    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.EmailParameter>> EmailParameters_GetByCodesAsync(string appcode, System.Collections.Generic.List<string> codes, string groupName)
    {
        return base.Channel.EmailParameters_GetByCodesAsync(appcode, codes, groupName);
    }

    public int EmailParameter_Update(PwC.C4.DataService.Model.EmailParameter emailParameter)
    {
        return base.Channel.EmailParameter_Update(emailParameter);
    }

    public System.Threading.Tasks.Task<int> EmailParameter_UpdateAsync(PwC.C4.DataService.Model.EmailParameter emailParameter)
    {
        return base.Channel.EmailParameter_UpdateAsync(emailParameter);
    }

    public bool EmailParameter_Delete(string appcode, int paraId, int modifyBy)
    {
        return base.Channel.EmailParameter_Delete(appcode, paraId, modifyBy);
    }

    public System.Threading.Tasks.Task<bool> EmailParameter_DeleteAsync(string appcode, int paraId, int modifyBy)
    {
        return base.Channel.EmailParameter_DeleteAsync(appcode, paraId, modifyBy);
    }

    public int EmailTemplate_Create(PwC.C4.DataService.Model.EmailTemplate model)
    {
        return base.Channel.EmailTemplate_Create(model);
    }

    public System.Threading.Tasks.Task<int> EmailTemplate_CreateAsync(PwC.C4.DataService.Model.EmailTemplate model)
    {
        return base.Channel.EmailTemplate_CreateAsync(model);
    }

    public PwC.C4.DataService.Model.EmailTemplate EmailTemplate_Get(string appcode, int tId)
    {
        return base.Channel.EmailTemplate_Get(appcode, tId);
    }

    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.EmailTemplate> EmailTemplate_GetAsync(string appcode, int tId)
    {
        return base.Channel.EmailTemplate_GetAsync(appcode, tId);
    }

    public System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate> EmailTemplates_GetByGroup(string appcode, string groupName)
    {
        return base.Channel.EmailTemplates_GetByGroup(appcode, groupName);
    }

    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate>> EmailTemplates_GetByGroupAsync(string appcode, string groupName)
    {
        return base.Channel.EmailTemplates_GetByGroupAsync(appcode, groupName);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    EmailTemplates_GetByPagingResponse IC4CommonService.EmailTemplates_GetByPaging(EmailTemplates_GetByPagingRequest request)
    {
        return base.Channel.EmailTemplates_GetByPaging(request);
    }

    public System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate> EmailTemplates_GetByPaging(string appcode, string name, int pageIndex, int pageSize, string groupName, out int totalCount)
    {
        EmailTemplates_GetByPagingRequest inValue = new EmailTemplates_GetByPagingRequest();
        inValue.appcode = appcode;
        inValue.name = name;
        inValue.pageIndex = pageIndex;
        inValue.pageSize = pageSize;
        inValue.groupName = groupName;
        EmailTemplates_GetByPagingResponse retVal = ((IC4CommonService)(this)).EmailTemplates_GetByPaging(inValue);
        totalCount = retVal.totalCount;
        return retVal.EmailTemplates_GetByPagingResult;
    }

    public System.Threading.Tasks.Task<EmailTemplates_GetByPagingResponse> EmailTemplates_GetByPagingAsync(EmailTemplates_GetByPagingRequest request)
    {
        return base.Channel.EmailTemplates_GetByPagingAsync(request);
    }

    public System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate> EmailTemplates_GetByCodes(string appcode, System.Collections.Generic.List<string> codes, string groupName)
    {
        return base.Channel.EmailTemplates_GetByCodes(appcode, codes, groupName);
    }

    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.EmailTemplate>> EmailTemplates_GetByCodesAsync(string appcode, System.Collections.Generic.List<string> codes, string groupName)
    {
        return base.Channel.EmailTemplates_GetByCodesAsync(appcode, codes, groupName);
    }

    public int EmailTemplate_Update(PwC.C4.DataService.Model.EmailTemplate emailTemplate)
    {
        return base.Channel.EmailTemplate_Update(emailTemplate);
    }

    public System.Threading.Tasks.Task<int> EmailTemplate_UpdateAsync(PwC.C4.DataService.Model.EmailTemplate emailTemplate)
    {
        return base.Channel.EmailTemplate_UpdateAsync(emailTemplate);
    }

    public bool EmailTemplate_Delete(string appcode, int tId, int modifyBy)
    {
        return base.Channel.EmailTemplate_Delete(appcode, tId, modifyBy);
    }

    public System.Threading.Tasks.Task<bool> EmailTemplate_DeleteAsync(string appcode, int tId, int modifyBy)
    {
        return base.Channel.EmailTemplate_DeleteAsync(appcode, tId, modifyBy);
    }

    public int InsertToMailQueue(PwC.C4.DataService.Model.MailQueueModel model)
    {
        return base.Channel.InsertToMailQueue(model);
    }

    public System.Threading.Tasks.Task<int> InsertToMailQueueAsync(PwC.C4.DataService.Model.MailQueueModel model)
    {
        return base.Channel.InsertToMailQueueAsync(model);
    }

    public int InsertToMailQueueWithAttachment(PwC.C4.DataService.Model.MailQueueModel model, System.Collections.Generic.List<PwC.C4.DataService.Model.MailAttachment> attachments)
    {
        return base.Channel.InsertToMailQueueWithAttachment(model, attachments);
    }

    public System.Threading.Tasks.Task<int> InsertToMailQueueWithAttachmentAsync(PwC.C4.DataService.Model.MailQueueModel model, System.Collections.Generic.List<PwC.C4.DataService.Model.MailAttachment> attachments)
    {
        return base.Channel.InsertToMailQueueWithAttachmentAsync(model, attachments);
    }

    public int InsertToMailQueueWithAttachmentId(PwC.C4.DataService.Model.MailQueueModel model, System.Collections.Generic.List<int> attachmentIds)
    {
        return base.Channel.InsertToMailQueueWithAttachmentId(model, attachmentIds);
    }

    public System.Threading.Tasks.Task<int> InsertToMailQueueWithAttachmentIdAsync(PwC.C4.DataService.Model.MailQueueModel model, System.Collections.Generic.List<int> attachmentIds)
    {
        return base.Channel.InsertToMailQueueWithAttachmentIdAsync(model, attachmentIds);
    }

    public int InsertToMailAttachment(PwC.C4.DataService.Model.MailAttachment attachment)
    {
        return base.Channel.InsertToMailAttachment(attachment);
    }

    public System.Threading.Tasks.Task<int> InsertToMailAttachmentAsync(PwC.C4.DataService.Model.MailAttachment attachment)
    {
        return base.Channel.InsertToMailAttachmentAsync(attachment);
    }

    public PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetByFormId(string appcode, string entityName, int formId)
    {
        return base.Channel.WorkFlow_GetByFormId(appcode, entityName, formId);
    }

    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetByFormIdAsync(string appcode, string entityName, int formId)
    {
        return base.Channel.WorkFlow_GetByFormIdAsync(appcode, entityName, formId);
    }

    public PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetByRecordId(string appcode, string entityName, string recordId)
    {
        return base.Channel.WorkFlow_GetByRecordId(appcode, entityName, recordId);
    }

    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetByRecordIdAsync(string appcode, string entityName, string recordId)
    {
        return base.Channel.WorkFlow_GetByRecordIdAsync(appcode, entityName, recordId);
    }

    public PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetLastUnactivedByInstanceId(string appcode, string workflowCode, int instanceId)
    {
        return base.Channel.WorkFlow_GetLastUnactivedByInstanceId(appcode, workflowCode, instanceId);
    }

    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetLastUnactivedByInstanceIdAsync(string appcode, string workflowCode, int instanceId)
    {
        return base.Channel.WorkFlow_GetLastUnactivedByInstanceIdAsync(appcode, workflowCode, instanceId);
    }

    public PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetLastUnactivedByRecordId(string appcode, string entityName, string recordId)
    {
        return base.Channel.WorkFlow_GetLastUnactivedByRecordId(appcode, entityName, recordId);
    }

    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetLastUnactivedByRecordIdAsync(string appcode, string entityName, string recordId)
    {
        return base.Channel.WorkFlow_GetLastUnactivedByRecordIdAsync(appcode, entityName, recordId);
    }

    public PwC.C4.DataService.Model.WorkflowBase WorkFlow_GetActiveByInstanceId(string appcode, int instanceId)
    {
        return base.Channel.WorkFlow_GetActiveByInstanceId(appcode, instanceId);
    }

    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.WorkflowBase> WorkFlow_GetActiveByInstanceIdAsync(string appcode, int instanceId)
    {
        return base.Channel.WorkFlow_GetActiveByInstanceIdAsync(appcode, instanceId);
    }

    public int Workflow_Insert(PwC.C4.DataService.Model.WorkflowBase model)
    {
        return base.Channel.Workflow_Insert(model);
    }

    public System.Threading.Tasks.Task<int> Workflow_InsertAsync(PwC.C4.DataService.Model.WorkflowBase model)
    {
        return base.Channel.Workflow_InsertAsync(model);
    }

    public PwC.C4.DataService.Model.StaffInfo Staff_Get(string staffId)
    {
        return base.Channel.Staff_Get(staffId);
    }

    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.StaffInfo> Staff_GetAsync(string staffId)
    {
        return base.Channel.Staff_GetAsync(staffId);
    }

    public System.Collections.Generic.List<PwC.C4.DataService.Model.StaffInfo> Staff_GetList(string where)
    {
        return base.Channel.Staff_GetList(where);
    }

    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.StaffInfo>> Staff_GetListAsync(string where)
    {
        return base.Channel.Staff_GetListAsync(where);
    }
}
