//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PwC.C4.Configuration.WcfSettings;

namespace PwC.C4.DataService.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailQueueModelStream", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class MailQueueModelStream : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppCodeField;
        
        private string ContentField;
        
        private string ImmediateFlagField;
        
        private string MailBccField;
        
        private string MailCcField;
        
        private string MailFromField;
        
        private string MailToField;
        
        private string OrganisationField;
        
        private string ReplyToField;
        
        private System.DateTime SendDateField;
        
        private string SendFromField;
        
        private string SubjectField;
        
        private string SubmitByField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImmediateFlag
        {
            get
            {
                return this.ImmediateFlagField;
            }
            set
            {
                this.ImmediateFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailBcc
        {
            get
            {
                return this.MailBccField;
            }
            set
            {
                this.MailBccField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCc
        {
            get
            {
                return this.MailCcField;
            }
            set
            {
                this.MailCcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailFrom
        {
            get
            {
                return this.MailFromField;
            }
            set
            {
                this.MailFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailTo
        {
            get
            {
                return this.MailToField;
            }
            set
            {
                this.MailToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organisation
        {
            get
            {
                return this.OrganisationField;
            }
            set
            {
                this.OrganisationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplyTo
        {
            get
            {
                return this.ReplyToField;
            }
            set
            {
                this.ReplyToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendFrom
        {
            get
            {
                return this.SendFromField;
            }
            set
            {
                this.SendFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitBy
        {
            get
            {
                return this.SubmitByField;
            }
            set
            {
                this.SubmitByField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailAttachment", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class MailAttachment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.IO.Stream ContentField;
        
        private string FileNameField;
        
        private bool LinkedResourceFlagField;
        
        private string MimeTypeField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.Stream Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LinkedResourceFlag
        {
            get
            {
                return this.LinkedResourceFlagField;
            }
            set
            {
                this.LinkedResourceFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IC4MailMasterService")]
public interface IC4MailMasterService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MailMasterService/InsertToMailQueue", ReplyAction="http://tempuri.org/IC4MailMasterService/InsertToMailQueueResponse")]
    int InsertToMailQueue(PwC.C4.DataService.Model.MailQueueModelStream model);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MailMasterService/InsertToMailQueue", ReplyAction="http://tempuri.org/IC4MailMasterService/InsertToMailQueueResponse")]
    System.Threading.Tasks.Task<int> InsertToMailQueueAsync(PwC.C4.DataService.Model.MailQueueModelStream model);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MailMasterService/InsertToMailQueueWithAttachment", ReplyAction="http://tempuri.org/IC4MailMasterService/InsertToMailQueueWithAttachmentResponse")]
    int InsertToMailQueueWithAttachment(PwC.C4.DataService.Model.MailQueueModelStream model, System.Collections.Generic.List<PwC.C4.DataService.Model.MailAttachment> attachments);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MailMasterService/InsertToMailQueueWithAttachment", ReplyAction="http://tempuri.org/IC4MailMasterService/InsertToMailQueueWithAttachmentResponse")]
    System.Threading.Tasks.Task<int> InsertToMailQueueWithAttachmentAsync(PwC.C4.DataService.Model.MailQueueModelStream model, System.Collections.Generic.List<PwC.C4.DataService.Model.MailAttachment> attachments);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MailMasterService/InsertToMailQueueWithAttachmentId", ReplyAction="http://tempuri.org/IC4MailMasterService/InsertToMailQueueWithAttachmentIdResponse" +
        "")]
    int InsertToMailQueueWithAttachmentId(PwC.C4.DataService.Model.MailQueueModelStream model, System.Collections.Generic.List<int> attachmentIds);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MailMasterService/InsertToMailQueueWithAttachmentId", ReplyAction="http://tempuri.org/IC4MailMasterService/InsertToMailQueueWithAttachmentIdResponse" +
        "")]
    System.Threading.Tasks.Task<int> InsertToMailQueueWithAttachmentIdAsync(PwC.C4.DataService.Model.MailQueueModelStream model, System.Collections.Generic.List<int> attachmentIds);
    
    // CODEGEN: Generating message contract since the wrapper name (MailAttachment) of message MailAttachment does not match the default value (InsertToMailAttachment)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MailMasterService/InsertToMailAttachment", ReplyAction="http://tempuri.org/IC4MailMasterService/InsertToMailAttachmentResponse")]
    MailMessageResult InsertToMailAttachment(MailAttachment request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MailMasterService/InsertToMailAttachment", ReplyAction="http://tempuri.org/IC4MailMasterService/InsertToMailAttachmentResponse")]
    System.Threading.Tasks.Task<MailMessageResult> InsertToMailAttachmentAsync(MailAttachment request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="MailAttachment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class MailAttachment
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public string FileName;
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public bool LinkedResourceFlag;
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public string MimeType;
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public string Name;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public System.IO.Stream Content;
    
    public MailAttachment()
    {
    }
    
    public MailAttachment(string FileName, bool LinkedResourceFlag, string MimeType, string Name, System.IO.Stream Content)
    {
        this.FileName = FileName;
        this.LinkedResourceFlag = LinkedResourceFlag;
        this.MimeType = MimeType;
        this.Name = Name;
        this.Content = Content;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="MailMessageResult", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class MailMessageResult
{
    
    public MailMessageResult()
    {
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IC4MailMasterServiceChannel : IC4MailMasterService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class C4MailMasterServiceClient : System.ServiceModel.ClientBase<IC4MailMasterService>, IC4MailMasterService
{
    static WcfSetting wcfSettings = WcfSettings.Instance.GetWcfSetting("C4MailMasterService");
    public C4MailMasterServiceClient() : this(wcfSettings.Binding, wcfSettings.Endpoint)
    {
    }
    
    public C4MailMasterServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public C4MailMasterServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public C4MailMasterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public C4MailMasterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int InsertToMailQueue(PwC.C4.DataService.Model.MailQueueModelStream model)
    {
        return base.Channel.InsertToMailQueue(model);
    }
    
    public System.Threading.Tasks.Task<int> InsertToMailQueueAsync(PwC.C4.DataService.Model.MailQueueModelStream model)
    {
        return base.Channel.InsertToMailQueueAsync(model);
    }
    
    public int InsertToMailQueueWithAttachment(PwC.C4.DataService.Model.MailQueueModelStream model, System.Collections.Generic.List<PwC.C4.DataService.Model.MailAttachment> attachments)
    {
        return base.Channel.InsertToMailQueueWithAttachment(model, attachments);
    }
    
    public System.Threading.Tasks.Task<int> InsertToMailQueueWithAttachmentAsync(PwC.C4.DataService.Model.MailQueueModelStream model, System.Collections.Generic.List<PwC.C4.DataService.Model.MailAttachment> attachments)
    {
        return base.Channel.InsertToMailQueueWithAttachmentAsync(model, attachments);
    }
    
    public int InsertToMailQueueWithAttachmentId(PwC.C4.DataService.Model.MailQueueModelStream model, System.Collections.Generic.List<int> attachmentIds)
    {
        return base.Channel.InsertToMailQueueWithAttachmentId(model, attachmentIds);
    }
    
    public System.Threading.Tasks.Task<int> InsertToMailQueueWithAttachmentIdAsync(PwC.C4.DataService.Model.MailQueueModelStream model, System.Collections.Generic.List<int> attachmentIds)
    {
        return base.Channel.InsertToMailQueueWithAttachmentIdAsync(model, attachmentIds);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    MailMessageResult IC4MailMasterService.InsertToMailAttachment(MailAttachment request)
    {
        return base.Channel.InsertToMailAttachment(request);
    }
    
    public void InsertToMailAttachment(string FileName, bool LinkedResourceFlag, string MimeType, string Name, System.IO.Stream Content)
    {
        MailAttachment inValue = new MailAttachment();
        inValue.FileName = FileName;
        inValue.LinkedResourceFlag = LinkedResourceFlag;
        inValue.MimeType = MimeType;
        inValue.Name = Name;
        inValue.Content = Content;
        MailMessageResult retVal = ((IC4MailMasterService)(this)).InsertToMailAttachment(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<MailMessageResult> IC4MailMasterService.InsertToMailAttachmentAsync(MailAttachment request)
    {
        return base.Channel.InsertToMailAttachmentAsync(request);
    }
    
    public System.Threading.Tasks.Task<MailMessageResult> InsertToMailAttachmentAsync(string FileName, bool LinkedResourceFlag, string MimeType, string Name, System.IO.Stream Content)
    {
        MailAttachment inValue = new MailAttachment();
        inValue.FileName = FileName;
        inValue.LinkedResourceFlag = LinkedResourceFlag;
        inValue.MimeType = MimeType;
        inValue.Name = Name;
        inValue.Content = Content;
        return ((IC4MailMasterService)(this)).InsertToMailAttachmentAsync(inValue);
    }
}
