//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PwC.C4.DataService.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSourceObject", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class DataSourceObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescField;
        
        private System.Guid IdField;
        
        private string KeyField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSourceBase", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class DataSourceBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private string NameField;
        
        private int OrderField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSourceTypeInfo", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class DataSourceTypeInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppCodeField;
        
        private string CreateByField;
        
        private string DescField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        private int OrderField;
        
        private int StateField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSourceDetail", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class DataSourceDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppCodeField;
        
        private string CreateByField;
        
        private System.DateTime CreateTimeField;
        
        private System.Guid DataSourceTypeIdField;
        
        private string DataSourceTypeNameField;
        
        private string GroupField;
        
        private System.Guid IdField;
        
        private string KeyField;
        
        private string ModifyByField;
        
        private System.DateTime ModifyTimeField;
        
        private string NameField;
        
        private int OrderField;
        
        private int StateField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DataSourceTypeId
        {
            get
            {
                return this.DataSourceTypeIdField;
            }
            set
            {
                this.DataSourceTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSourceTypeName
        {
            get
            {
                return this.DataSourceTypeNameField;
            }
            set
            {
                this.DataSourceTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyBy
        {
            get
            {
                return this.ModifyByField;
            }
            set
            {
                this.ModifyByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyTime
        {
            get
            {
                return this.ModifyTimeField;
            }
            set
            {
                this.ModifyTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSourceDelete", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class DataSourceDelete : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppCodeField;
        
        private System.Guid IdField;
        
        private string ModifyByField;
        
        private PwC.C4.DataService.Model.Enum.DataSource TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyBy
        {
            get
            {
                return this.ModifyByField;
            }
            set
            {
                this.ModifyByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PwC.C4.DataService.Model.Enum.DataSource Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HtmlSnippet", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class HtmlSnippet : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppCodeField;
        
        private string CodeField;
        
        private PwC.C4.DataService.Model.Enum.HtmlSnippetType ControlTypeField;
        
        private string CreateByField;
        
        private System.DateTime CreateTimeField;
        
        private string DescriptionField;
        
        private string GroupField;
        
        private string HtmlField;
        
        private System.Guid IdField;
        
        private bool IsDeletedField;
        
        private string ModifyByField;
        
        private System.DateTime ModifyTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PwC.C4.DataService.Model.Enum.HtmlSnippetType ControlType
        {
            get
            {
                return this.ControlTypeField;
            }
            set
            {
                this.ControlTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Html
        {
            get
            {
                return this.HtmlField;
            }
            set
            {
                this.HtmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyBy
        {
            get
            {
                return this.ModifyByField;
            }
            set
            {
                this.ModifyByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyTime
        {
            get
            {
                return this.ModifyTimeField;
            }
            set
            {
                this.ModifyTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HtmlCategory", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class HtmlCategory : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppCodeField;
        
        private string CodeField;
        
        private string CreateByField;
        
        private System.DateTime CreateTimeField;
        
        private string DescriptionField;
        
        private string DisplayNameField;
        
        private string FuncField;
        
        private string GroupField;
        
        private string IconField;
        
        private System.Guid IdField;
        
        private bool IsCollapseField;
        
        private bool IsDeletedField;
        
        private int LevelField;
        
        private string ModifyByField;
        
        private System.DateTime ModifyTimeField;
        
        private int OrderField;
        
        private System.Collections.Generic.Dictionary<string, string> ParameterDicField;
        
        private string ParametersField;
        
        private System.Guid ParentIdField;
        
        private int StatusField;
        
        private System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> SubCategoriesField;
        
        private int TypeField;
        
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Func
        {
            get
            {
                return this.FuncField;
            }
            set
            {
                this.FuncField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icon
        {
            get
            {
                return this.IconField;
            }
            set
            {
                this.IconField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCollapse
        {
            get
            {
                return this.IsCollapseField;
            }
            set
            {
                this.IsCollapseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyBy
        {
            get
            {
                return this.ModifyByField;
            }
            set
            {
                this.ModifyByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyTime
        {
            get
            {
                return this.ModifyTimeField;
            }
            set
            {
                this.ModifyTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ParameterDic
        {
            get
            {
                return this.ParameterDicField;
            }
            set
            {
                this.ParameterDicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ParentId
        {
            get
            {
                return this.ParentIdField;
            }
            set
            {
                this.ParentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> SubCategories
        {
            get
            {
                return this.SubCategoriesField;
            }
            set
            {
                this.SubCategoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
}
namespace PwC.C4.DataService.Model.Enum
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSource", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model.Enum")]
    public enum DataSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Type = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Detail = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HtmlSnippetType", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model.Enum")]
    public enum HtmlSnippetType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Script = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Style = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rzaor = 4,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IC4DataService")]
public interface IC4DataService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/DataSourceObjects_Get", ReplyAction="http://tempuri.org/IC4DataService/DataSourceObjects_GetResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceObject> DataSourceObjects_Get(string appcode, string dataSourceType, string group);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/DataSourceObjects_Get", ReplyAction="http://tempuri.org/IC4DataService/DataSourceObjects_GetResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceObject>> DataSourceObjects_GetAsync(string appcode, string dataSourceType, string group);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/DataSourceBase_Get", ReplyAction="http://tempuri.org/IC4DataService/DataSourceBase_GetResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceBase> DataSourceBase_Get(string appCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/DataSourceBase_Get", ReplyAction="http://tempuri.org/IC4DataService/DataSourceBase_GetResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceBase>> DataSourceBase_GetAsync(string appCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/DataSource_GetType", ReplyAction="http://tempuri.org/IC4DataService/DataSource_GetTypeResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceTypeInfo> DataSource_GetType(string appCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/DataSource_GetType", ReplyAction="http://tempuri.org/IC4DataService/DataSource_GetTypeResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceTypeInfo>> DataSource_GetTypeAsync(string appCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/UpdateDataSourceType", ReplyAction="http://tempuri.org/IC4DataService/UpdateDataSourceTypeResponse")]
    bool UpdateDataSourceType(PwC.C4.DataService.Model.DataSourceTypeInfo type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/UpdateDataSourceType", ReplyAction="http://tempuri.org/IC4DataService/UpdateDataSourceTypeResponse")]
    System.Threading.Tasks.Task<bool> UpdateDataSourceTypeAsync(PwC.C4.DataService.Model.DataSourceTypeInfo type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/UpdateDataSourceDetail", ReplyAction="http://tempuri.org/IC4DataService/UpdateDataSourceDetailResponse")]
    bool UpdateDataSourceDetail(PwC.C4.DataService.Model.DataSourceDetail detail);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/UpdateDataSourceDetail", ReplyAction="http://tempuri.org/IC4DataService/UpdateDataSourceDetailResponse")]
    System.Threading.Tasks.Task<bool> UpdateDataSourceDetailAsync(PwC.C4.DataService.Model.DataSourceDetail detail);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/DeleteDataSource", ReplyAction="http://tempuri.org/IC4DataService/DeleteDataSourceResponse")]
    bool DeleteDataSource(PwC.C4.DataService.Model.DataSourceDelete delete);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/DeleteDataSource", ReplyAction="http://tempuri.org/IC4DataService/DeleteDataSourceResponse")]
    System.Threading.Tasks.Task<bool> DeleteDataSourceAsync(PwC.C4.DataService.Model.DataSourceDelete delete);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetDataSourceDetails", ReplyAction="http://tempuri.org/IC4DataService/GetDataSourceDetailsResponse")]
    GetDataSourceDetailsResponse GetDataSourceDetails(GetDataSourceDetailsRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetDataSourceDetails", ReplyAction="http://tempuri.org/IC4DataService/GetDataSourceDetailsResponse")]
    System.Threading.Tasks.Task<GetDataSourceDetailsResponse> GetDataSourceDetailsAsync(GetDataSourceDetailsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/HtmlSnippet_Get", ReplyAction="http://tempuri.org/IC4DataService/HtmlSnippet_GetResponse")]
    PwC.C4.DataService.Model.HtmlSnippet HtmlSnippet_Get(string appCode, string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/HtmlSnippet_Get", ReplyAction="http://tempuri.org/IC4DataService/HtmlSnippet_GetResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.HtmlSnippet> HtmlSnippet_GetAsync(string appCode, string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ByCode", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ByCodeResponse")]
    PwC.C4.DataService.Model.HtmlCategory GetHtmlCategory_ByCode(string appCode, string group, string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ByCode", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ByCodeResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ByCodeAsync(string appCode, string group, string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ById", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ByIdResponse")]
    PwC.C4.DataService.Model.HtmlCategory GetHtmlCategory_ById(string appCode, string group, System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ById", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ByIdResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ByIdAsync(string appCode, string group, System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByAppCode", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByAppCodeResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ListByAppCode(string appCode, string group);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByAppCode", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByAppCodeResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory>> GetHtmlCategory_ListByAppCodeAsync(string appCode, string group);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByRole", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByRoleResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ListByRole(string appCode, string group, System.Collections.Generic.List<string> roles);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByRole", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByRoleResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory>> GetHtmlCategory_ListByRoleAsync(string appCode, string group, System.Collections.Generic.List<string> roles);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByParentId", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByParentIdResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ListByParentId(string appCode, string group, System.Guid parentId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByParentId", ReplyAction="http://tempuri.org/IC4DataService/GetHtmlCategory_ListByParentIdResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory>> GetHtmlCategory_ListByParentIdAsync(string appCode, string group, System.Guid parentId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/HtmlCategory_Delete", ReplyAction="http://tempuri.org/IC4DataService/HtmlCategory_DeleteResponse")]
    bool HtmlCategory_Delete(string appCode, string group, System.Collections.Generic.List<System.Guid> ids, string modifyBy);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/HtmlCategory_Delete", ReplyAction="http://tempuri.org/IC4DataService/HtmlCategory_DeleteResponse")]
    System.Threading.Tasks.Task<bool> HtmlCategory_DeleteAsync(string appCode, string group, System.Collections.Generic.List<System.Guid> ids, string modifyBy);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/HtmlCategory_Update", ReplyAction="http://tempuri.org/IC4DataService/HtmlCategory_UpdateResponse")]
    int HtmlCategory_Update(PwC.C4.DataService.Model.HtmlCategory entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/HtmlCategory_Update", ReplyAction="http://tempuri.org/IC4DataService/HtmlCategory_UpdateResponse")]
    System.Threading.Tasks.Task<int> HtmlCategory_UpdateAsync(PwC.C4.DataService.Model.HtmlCategory entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/HtmlCategory_GetByGroup", ReplyAction="http://tempuri.org/IC4DataService/HtmlCategory_GetByGroupResponse")]
    System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> HtmlCategory_GetByGroup(string appCode, string group, System.Collections.Generic.List<System.Guid> collapseIds);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4DataService/HtmlCategory_GetByGroup", ReplyAction="http://tempuri.org/IC4DataService/HtmlCategory_GetByGroupResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory>> HtmlCategory_GetByGroupAsync(string appCode, string group, System.Collections.Generic.List<System.Guid> collapseIds);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSourceDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataSourceDetailsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string appCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string code;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public string group;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
    public System.Nullable<System.Guid> typeId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
    public int page;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
    public int size;
    
    public GetDataSourceDetailsRequest()
    {
    }
    
    public GetDataSourceDetailsRequest(string appCode, string code, string group, System.Nullable<System.Guid> typeId, int page, int size)
    {
        this.appCode = appCode;
        this.code = code;
        this.group = group;
        this.typeId = typeId;
        this.page = page;
        this.size = size;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSourceDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataSourceDetailsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceDetail> GetDataSourceDetailsResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public int totalCount;
    
    public GetDataSourceDetailsResponse()
    {
    }
    
    public GetDataSourceDetailsResponse(System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceDetail> GetDataSourceDetailsResult, int totalCount)
    {
        this.GetDataSourceDetailsResult = GetDataSourceDetailsResult;
        this.totalCount = totalCount;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IC4DataServiceChannel : IC4DataService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class C4DataServiceClient : System.ServiceModel.ClientBase<IC4DataService>, IC4DataService
{
    
    public C4DataServiceClient()
    {
    }
    
    public C4DataServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public C4DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public C4DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public C4DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceObject> DataSourceObjects_Get(string appcode, string dataSourceType, string group)
    {
        return base.Channel.DataSourceObjects_Get(appcode, dataSourceType, group);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceObject>> DataSourceObjects_GetAsync(string appcode, string dataSourceType, string group)
    {
        return base.Channel.DataSourceObjects_GetAsync(appcode, dataSourceType, group);
    }
    
    public System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceBase> DataSourceBase_Get(string appCode)
    {
        return base.Channel.DataSourceBase_Get(appCode);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceBase>> DataSourceBase_GetAsync(string appCode)
    {
        return base.Channel.DataSourceBase_GetAsync(appCode);
    }
    
    public System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceTypeInfo> DataSource_GetType(string appCode)
    {
        return base.Channel.DataSource_GetType(appCode);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceTypeInfo>> DataSource_GetTypeAsync(string appCode)
    {
        return base.Channel.DataSource_GetTypeAsync(appCode);
    }
    
    public bool UpdateDataSourceType(PwC.C4.DataService.Model.DataSourceTypeInfo type)
    {
        return base.Channel.UpdateDataSourceType(type);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateDataSourceTypeAsync(PwC.C4.DataService.Model.DataSourceTypeInfo type)
    {
        return base.Channel.UpdateDataSourceTypeAsync(type);
    }
    
    public bool UpdateDataSourceDetail(PwC.C4.DataService.Model.DataSourceDetail detail)
    {
        return base.Channel.UpdateDataSourceDetail(detail);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateDataSourceDetailAsync(PwC.C4.DataService.Model.DataSourceDetail detail)
    {
        return base.Channel.UpdateDataSourceDetailAsync(detail);
    }
    
    public bool DeleteDataSource(PwC.C4.DataService.Model.DataSourceDelete delete)
    {
        return base.Channel.DeleteDataSource(delete);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteDataSourceAsync(PwC.C4.DataService.Model.DataSourceDelete delete)
    {
        return base.Channel.DeleteDataSourceAsync(delete);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataSourceDetailsResponse IC4DataService.GetDataSourceDetails(GetDataSourceDetailsRequest request)
    {
        return base.Channel.GetDataSourceDetails(request);
    }
    
    public System.Collections.Generic.List<PwC.C4.DataService.Model.DataSourceDetail> GetDataSourceDetails(string appCode, string code, string group, System.Nullable<System.Guid> typeId, int page, int size, out int totalCount)
    {
        GetDataSourceDetailsRequest inValue = new GetDataSourceDetailsRequest();
        inValue.appCode = appCode;
        inValue.code = code;
        inValue.group = group;
        inValue.typeId = typeId;
        inValue.page = page;
        inValue.size = size;
        GetDataSourceDetailsResponse retVal = ((IC4DataService)(this)).GetDataSourceDetails(inValue);
        totalCount = retVal.totalCount;
        return retVal.GetDataSourceDetailsResult;
    }
    
    public System.Threading.Tasks.Task<GetDataSourceDetailsResponse> GetDataSourceDetailsAsync(GetDataSourceDetailsRequest request)
    {
        return base.Channel.GetDataSourceDetailsAsync(request);
    }
    
    public PwC.C4.DataService.Model.HtmlSnippet HtmlSnippet_Get(string appCode, string code)
    {
        return base.Channel.HtmlSnippet_Get(appCode, code);
    }
    
    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.HtmlSnippet> HtmlSnippet_GetAsync(string appCode, string code)
    {
        return base.Channel.HtmlSnippet_GetAsync(appCode, code);
    }
    
    public PwC.C4.DataService.Model.HtmlCategory GetHtmlCategory_ByCode(string appCode, string group, string code)
    {
        return base.Channel.GetHtmlCategory_ByCode(appCode, group, code);
    }
    
    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ByCodeAsync(string appCode, string group, string code)
    {
        return base.Channel.GetHtmlCategory_ByCodeAsync(appCode, group, code);
    }
    
    public PwC.C4.DataService.Model.HtmlCategory GetHtmlCategory_ById(string appCode, string group, System.Guid id)
    {
        return base.Channel.GetHtmlCategory_ById(appCode, group, id);
    }
    
    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ByIdAsync(string appCode, string group, System.Guid id)
    {
        return base.Channel.GetHtmlCategory_ByIdAsync(appCode, group, id);
    }
    
    public System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ListByAppCode(string appCode, string group)
    {
        return base.Channel.GetHtmlCategory_ListByAppCode(appCode, group);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory>> GetHtmlCategory_ListByAppCodeAsync(string appCode, string group)
    {
        return base.Channel.GetHtmlCategory_ListByAppCodeAsync(appCode, group);
    }
    
    public System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ListByRole(string appCode, string group, System.Collections.Generic.List<string> roles)
    {
        return base.Channel.GetHtmlCategory_ListByRole(appCode, group, roles);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory>> GetHtmlCategory_ListByRoleAsync(string appCode, string group, System.Collections.Generic.List<string> roles)
    {
        return base.Channel.GetHtmlCategory_ListByRoleAsync(appCode, group, roles);
    }
    
    public System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> GetHtmlCategory_ListByParentId(string appCode, string group, System.Guid parentId)
    {
        return base.Channel.GetHtmlCategory_ListByParentId(appCode, group, parentId);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory>> GetHtmlCategory_ListByParentIdAsync(string appCode, string group, System.Guid parentId)
    {
        return base.Channel.GetHtmlCategory_ListByParentIdAsync(appCode, group, parentId);
    }
    
    public bool HtmlCategory_Delete(string appCode, string group, System.Collections.Generic.List<System.Guid> ids, string modifyBy)
    {
        return base.Channel.HtmlCategory_Delete(appCode, group, ids, modifyBy);
    }
    
    public System.Threading.Tasks.Task<bool> HtmlCategory_DeleteAsync(string appCode, string group, System.Collections.Generic.List<System.Guid> ids, string modifyBy)
    {
        return base.Channel.HtmlCategory_DeleteAsync(appCode, group, ids, modifyBy);
    }
    
    public int HtmlCategory_Update(PwC.C4.DataService.Model.HtmlCategory entity)
    {
        return base.Channel.HtmlCategory_Update(entity);
    }
    
    public System.Threading.Tasks.Task<int> HtmlCategory_UpdateAsync(PwC.C4.DataService.Model.HtmlCategory entity)
    {
        return base.Channel.HtmlCategory_UpdateAsync(entity);
    }
    
    public System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory> HtmlCategory_GetByGroup(string appCode, string group, System.Collections.Generic.List<System.Guid> collapseIds)
    {
        return base.Channel.HtmlCategory_GetByGroup(appCode, group, collapseIds);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.DataService.Model.HtmlCategory>> HtmlCategory_GetByGroupAsync(string appCode, string group, System.Collections.Generic.List<System.Guid> collapseIds)
    {
        return base.Channel.HtmlCategory_GetByGroupAsync(appCode, group, collapseIds);
    }
}
