//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PwC.C4.DataService.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionCheck", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class FunctionCheck : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ActionField;
        
        private string AppCodeField;
        
        private string AreaField;
        
        private string ControllerField;
        
        private System.Collections.Generic.List<string> RoleNameField;
        
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Controller
        {
            get
            {
                return this.ControllerField;
            }
            set
            {
                this.ControllerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
}
namespace PwC.C4.DataService.Model.Enum
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionCheckResult", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model.Enum")]
    public enum FunctionCheckResult : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPermissions = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Permissioned = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RoleNotExist = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunctionNotExist = 3,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IC4MembershipService")]
public interface IC4MembershipService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MembershipService/CheckFunctionRight", ReplyAction="http://tempuri.org/IC4MembershipService/CheckFunctionRightResponse")]
    PwC.C4.DataService.Model.Enum.FunctionCheckResult CheckFunctionRight(PwC.C4.DataService.Model.FunctionCheck functionCheck);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4MembershipService/CheckFunctionRight", ReplyAction="http://tempuri.org/IC4MembershipService/CheckFunctionRightResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.Enum.FunctionCheckResult> CheckFunctionRightAsync(PwC.C4.DataService.Model.FunctionCheck functionCheck);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IC4MembershipServiceChannel : IC4MembershipService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class C4MembershipServiceClient : System.ServiceModel.ClientBase<IC4MembershipService>, IC4MembershipService
{
    
    public C4MembershipServiceClient()
    {
    }
    
    public C4MembershipServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public C4MembershipServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public C4MembershipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public C4MembershipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public PwC.C4.DataService.Model.Enum.FunctionCheckResult CheckFunctionRight(PwC.C4.DataService.Model.FunctionCheck functionCheck)
    {
        return base.Channel.CheckFunctionRight(functionCheck);
    }
    
    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.Enum.FunctionCheckResult> CheckFunctionRightAsync(PwC.C4.DataService.Model.FunctionCheck functionCheck)
    {
        return base.Channel.CheckFunctionRightAsync(functionCheck);
    }
}
