//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IC4PreferenceService")]
public interface IC4PreferenceService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4PreferenceService/Get", ReplyAction="http://tempuri.org/IC4PreferenceService/GetResponse")]
    string Get(string key);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4PreferenceService/Get", ReplyAction="http://tempuri.org/IC4PreferenceService/GetResponse")]
    System.Threading.Tasks.Task<string> GetAsync(string key);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4PreferenceService/Set", ReplyAction="http://tempuri.org/IC4PreferenceService/SetResponse")]
    bool Set(string key, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4PreferenceService/Set", ReplyAction="http://tempuri.org/IC4PreferenceService/SetResponse")]
    System.Threading.Tasks.Task<bool> SetAsync(string key, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4PreferenceService/DeleteKey", ReplyAction="http://tempuri.org/IC4PreferenceService/DeleteKeyResponse")]
    bool DeleteKey(string key);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IC4PreferenceService/DeleteKey", ReplyAction="http://tempuri.org/IC4PreferenceService/DeleteKeyResponse")]
    System.Threading.Tasks.Task<bool> DeleteKeyAsync(string key);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IC4PreferenceServiceChannel : IC4PreferenceService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class C4PreferenceServiceClient : System.ServiceModel.ClientBase<IC4PreferenceService>, IC4PreferenceService
{
    
    public C4PreferenceServiceClient()
    {
    }
    
    public C4PreferenceServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public C4PreferenceServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public C4PreferenceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public C4PreferenceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Get(string key)
    {
        return base.Channel.Get(key);
    }
    
    public System.Threading.Tasks.Task<string> GetAsync(string key)
    {
        return base.Channel.GetAsync(key);
    }
    
    public bool Set(string key, string value)
    {
        return base.Channel.Set(key, value);
    }
    
    public System.Threading.Tasks.Task<bool> SetAsync(string key, string value)
    {
        return base.Channel.SetAsync(key, value);
    }
    
    public bool DeleteKey(string key)
    {
        return base.Channel.DeleteKey(key);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteKeyAsync(string key)
    {
        return base.Channel.DeleteKeyAsync(key);
    }
}
