//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PwC.C4.DataService.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailQueueModel", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class MailQueueModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppCodeField;
        
        private string ContentField;
        
        private string ImmediateFlagField;
        
        private string MailBccField;
        
        private string MailCcField;
        
        private string MailFromField;
        
        private string MailToField;
        
        private string OrganisationField;
        
        private string ReplyToField;
        
        private System.DateTime SendDateField;
        
        private string SendFromField;
        
        private string SubjectField;
        
        private string SubmitByField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImmediateFlag
        {
            get
            {
                return this.ImmediateFlagField;
            }
            set
            {
                this.ImmediateFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailBcc
        {
            get
            {
                return this.MailBccField;
            }
            set
            {
                this.MailBccField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCc
        {
            get
            {
                return this.MailCcField;
            }
            set
            {
                this.MailCcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailFrom
        {
            get
            {
                return this.MailFromField;
            }
            set
            {
                this.MailFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailTo
        {
            get
            {
                return this.MailToField;
            }
            set
            {
                this.MailToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organisation
        {
            get
            {
                return this.OrganisationField;
            }
            set
            {
                this.OrganisationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplyTo
        {
            get
            {
                return this.ReplyToField;
            }
            set
            {
                this.ReplyToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendFrom
        {
            get
            {
                return this.SendFromField;
            }
            set
            {
                this.SendFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitBy
        {
            get
            {
                return this.SubmitByField;
            }
            set
            {
                this.SubmitByField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffInfo", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class StaffInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BUField;
        
        private string BUDescField;
        
        private System.Nullable<System.DateTime> ContractYearEndField;
        
        private string CountryCodeField;
        
        private string CountryOfficeField;
        
        private string DepartmentField;
        
        private string DivCodeField;
        
        private string DivNameField;
        
        private string EmailField;
        
        private string EmployeeCategoryField;
        
        private string ExpatFlagField;
        
        private string FirstNameField;
        
        private string FullNameField;
        
        private string GUIDField;
        
        private string GivenNameField;
        
        private string GradeCodeField;
        
        private string GradeNameField;
        
        private string GroupCodeField;
        
        private string GroupNameField;
        
        private string HRIDField;
        
        private string IDTerritoryField;
        
        private string INetEmailField;
        
        private string IsProfessionalField;
        
        private string JobCodeField;
        
        private string JobGradeField;
        
        private string JobTitleField;
        
        private System.Nullable<System.DateTime> JoinDateField;
        
        private string LDAP_DistNameField;
        
        private string LastNameField;
        
        private string LoSField;
        
        private string LoginContextField;
        
        private string LoginIDField;
        
        private string MajorityField;
        
        private string MajorityCategoryField;
        
        private string NameInEngField;
        
        private string NativeNameField;
        
        private string NotesIDField;
        
        private string OUCodeField;
        
        private string OfficeBuildingField;
        
        private string OfficeCityNameField;
        
        private string OfficeFloorField;
        
        private string OfficePINField;
        
        private string PhoneNoField;
        
        private string PowerGradeCodeField;
        
        private string PowerGroupCodeField;
        
        private string PowerIDStatusField;
        
        private string PowerStaffCodeField;
        
        private string PreferredNameField;
        
        private string PwCEntityIDField;
        
        private string RoleField;
        
        private string SalaryCategoryField;
        
        private string SchoolUniversityField;
        
        private string SecNameField;
        
        private string SexField;
        
        private string StaffIdField;
        
        private string StaffInitialField;
        
        private string StaffNameField;
        
        private string StatusField;
        
        private string SubServiceField;
        
        private string SubServiceDescField;
        
        private System.Nullable<System.DateTime> TermDateField;
        
        private string TermFlagField;
        
        private System.Nullable<System.DateTime> TerritoryEffectiveDateField;
        
        private string localExpatFlagField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BU
        {
            get
            {
                return this.BUField;
            }
            set
            {
                this.BUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BUDesc
        {
            get
            {
                return this.BUDescField;
            }
            set
            {
                this.BUDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ContractYearEnd
        {
            get
            {
                return this.ContractYearEndField;
            }
            set
            {
                this.ContractYearEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryOffice
        {
            get
            {
                return this.CountryOfficeField;
            }
            set
            {
                this.CountryOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivCode
        {
            get
            {
                return this.DivCodeField;
            }
            set
            {
                this.DivCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivName
        {
            get
            {
                return this.DivNameField;
            }
            set
            {
                this.DivNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeCategory
        {
            get
            {
                return this.EmployeeCategoryField;
            }
            set
            {
                this.EmployeeCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpatFlag
        {
            get
            {
                return this.ExpatFlagField;
            }
            set
            {
                this.ExpatFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUID
        {
            get
            {
                return this.GUIDField;
            }
            set
            {
                this.GUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GivenName
        {
            get
            {
                return this.GivenNameField;
            }
            set
            {
                this.GivenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeCode
        {
            get
            {
                return this.GradeCodeField;
            }
            set
            {
                this.GradeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeName
        {
            get
            {
                return this.GradeNameField;
            }
            set
            {
                this.GradeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupCode
        {
            get
            {
                return this.GroupCodeField;
            }
            set
            {
                this.GroupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HRID
        {
            get
            {
                return this.HRIDField;
            }
            set
            {
                this.HRIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDTerritory
        {
            get
            {
                return this.IDTerritoryField;
            }
            set
            {
                this.IDTerritoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INetEmail
        {
            get
            {
                return this.INetEmailField;
            }
            set
            {
                this.INetEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsProfessional
        {
            get
            {
                return this.IsProfessionalField;
            }
            set
            {
                this.IsProfessionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobCode
        {
            get
            {
                return this.JobCodeField;
            }
            set
            {
                this.JobCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobGrade
        {
            get
            {
                return this.JobGradeField;
            }
            set
            {
                this.JobGradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle
        {
            get
            {
                return this.JobTitleField;
            }
            set
            {
                this.JobTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> JoinDate
        {
            get
            {
                return this.JoinDateField;
            }
            set
            {
                this.JoinDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LDAP_DistName
        {
            get
            {
                return this.LDAP_DistNameField;
            }
            set
            {
                this.LDAP_DistNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoS
        {
            get
            {
                return this.LoSField;
            }
            set
            {
                this.LoSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginContext
        {
            get
            {
                return this.LoginContextField;
            }
            set
            {
                this.LoginContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginID
        {
            get
            {
                return this.LoginIDField;
            }
            set
            {
                this.LoginIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Majority
        {
            get
            {
                return this.MajorityField;
            }
            set
            {
                this.MajorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorityCategory
        {
            get
            {
                return this.MajorityCategoryField;
            }
            set
            {
                this.MajorityCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameInEng
        {
            get
            {
                return this.NameInEngField;
            }
            set
            {
                this.NameInEngField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NativeName
        {
            get
            {
                return this.NativeNameField;
            }
            set
            {
                this.NativeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotesID
        {
            get
            {
                return this.NotesIDField;
            }
            set
            {
                this.NotesIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OUCode
        {
            get
            {
                return this.OUCodeField;
            }
            set
            {
                this.OUCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeBuilding
        {
            get
            {
                return this.OfficeBuildingField;
            }
            set
            {
                this.OfficeBuildingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeCityName
        {
            get
            {
                return this.OfficeCityNameField;
            }
            set
            {
                this.OfficeCityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeFloor
        {
            get
            {
                return this.OfficeFloorField;
            }
            set
            {
                this.OfficeFloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficePIN
        {
            get
            {
                return this.OfficePINField;
            }
            set
            {
                this.OfficePINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo
        {
            get
            {
                return this.PhoneNoField;
            }
            set
            {
                this.PhoneNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerGradeCode
        {
            get
            {
                return this.PowerGradeCodeField;
            }
            set
            {
                this.PowerGradeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerGroupCode
        {
            get
            {
                return this.PowerGroupCodeField;
            }
            set
            {
                this.PowerGroupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerIDStatus
        {
            get
            {
                return this.PowerIDStatusField;
            }
            set
            {
                this.PowerIDStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerStaffCode
        {
            get
            {
                return this.PowerStaffCodeField;
            }
            set
            {
                this.PowerStaffCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredName
        {
            get
            {
                return this.PreferredNameField;
            }
            set
            {
                this.PreferredNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PwCEntityID
        {
            get
            {
                return this.PwCEntityIDField;
            }
            set
            {
                this.PwCEntityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalaryCategory
        {
            get
            {
                return this.SalaryCategoryField;
            }
            set
            {
                this.SalaryCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolUniversity
        {
            get
            {
                return this.SchoolUniversityField;
            }
            set
            {
                this.SchoolUniversityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecName
        {
            get
            {
                return this.SecNameField;
            }
            set
            {
                this.SecNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffId
        {
            get
            {
                return this.StaffIdField;
            }
            set
            {
                this.StaffIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffInitial
        {
            get
            {
                return this.StaffInitialField;
            }
            set
            {
                this.StaffInitialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffName
        {
            get
            {
                return this.StaffNameField;
            }
            set
            {
                this.StaffNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubService
        {
            get
            {
                return this.SubServiceField;
            }
            set
            {
                this.SubServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubServiceDesc
        {
            get
            {
                return this.SubServiceDescField;
            }
            set
            {
                this.SubServiceDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TermDate
        {
            get
            {
                return this.TermDateField;
            }
            set
            {
                this.TermDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TermFlag
        {
            get
            {
                return this.TermFlagField;
            }
            set
            {
                this.TermFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TerritoryEffectiveDate
        {
            get
            {
                return this.TerritoryEffectiveDateField;
            }
            set
            {
                this.TerritoryEffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localExpatFlag
        {
            get
            {
                return this.localExpatFlagField;
            }
            set
            {
                this.localExpatFlagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invitation", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class Invitation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppCodeField;
        
        private string CreatedByField;
        
        private System.DateTime CreatedDateField;
        
        private string DescriptionField;
        
        private string EmailClientTypeField;
        
        private System.Guid InidField;
        
        private System.Nullable<System.DateTime> InvitationEndTimeField;
        
        private System.Nullable<System.DateTime> InvitationStartTimeField;
        
        private string InvitationTypeField;
        
        private System.Nullable<int> InvitationtimeZoneField;
        
        private string LocationField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        private string SendFlagField;
        
        private string SubjectField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailClientType
        {
            get
            {
                return this.EmailClientTypeField;
            }
            set
            {
                this.EmailClientTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Inid
        {
            get
            {
                return this.InidField;
            }
            set
            {
                this.InidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InvitationEndTime
        {
            get
            {
                return this.InvitationEndTimeField;
            }
            set
            {
                this.InvitationEndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InvitationStartTime
        {
            get
            {
                return this.InvitationStartTimeField;
            }
            set
            {
                this.InvitationStartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvitationType
        {
            get
            {
                return this.InvitationTypeField;
            }
            set
            {
                this.InvitationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InvitationtimeZone
        {
            get
            {
                return this.InvitationtimeZoneField;
            }
            set
            {
                this.InvitationtimeZoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendFlag
        {
            get
            {
                return this.SendFlagField;
            }
            set
            {
                this.SendFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvitationRole", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.DataService.Model")]
    public partial class InvitationRole : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid InidField;
        
        private string IsRequiredField;
        
        private string RoleEmailField;
        
        private int RoleIdField;
        
        private string RoleTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Inid
        {
            get
            {
                return this.InidField;
            }
            set
            {
                this.InidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleEmail
        {
            get
            {
                return this.RoleEmailField;
            }
            set
            {
                this.RoleEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleType
        {
            get
            {
                return this.RoleTypeField;
            }
            set
            {
                this.RoleTypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IInfrastructure")]
public interface IInfrastructure
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfrastructure/InsertToMailQueue", ReplyAction="http://tempuri.org/IInfrastructure/InsertToMailQueueResponse")]
    int InsertToMailQueue(PwC.C4.DataService.Model.MailQueueModel model);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfrastructure/InsertToMailQueue", ReplyAction="http://tempuri.org/IInfrastructure/InsertToMailQueueResponse")]
    System.Threading.Tasks.Task<int> InsertToMailQueueAsync(PwC.C4.DataService.Model.MailQueueModel model);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfrastructure/InsertToMailQueueBatch", ReplyAction="http://tempuri.org/IInfrastructure/InsertToMailQueueBatchResponse")]
    int InsertToMailQueueBatch(System.Collections.Generic.List<PwC.C4.DataService.Model.MailQueueModel> model);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfrastructure/InsertToMailQueueBatch", ReplyAction="http://tempuri.org/IInfrastructure/InsertToMailQueueBatchResponse")]
    System.Threading.Tasks.Task<int> InsertToMailQueueBatchAsync(System.Collections.Generic.List<PwC.C4.DataService.Model.MailQueueModel> model);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfrastructure/Staff_Get", ReplyAction="http://tempuri.org/IInfrastructure/Staff_GetResponse")]
    PwC.C4.DataService.Model.StaffInfo Staff_Get(string staffId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfrastructure/Staff_Get", ReplyAction="http://tempuri.org/IInfrastructure/Staff_GetResponse")]
    System.Threading.Tasks.Task<PwC.C4.DataService.Model.StaffInfo> Staff_GetAsync(string staffId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfrastructure/InsertInvitation", ReplyAction="http://tempuri.org/IInfrastructure/InsertInvitationResponse")]
    string InsertInvitation(PwC.C4.DataService.Model.Invitation invitation, System.Collections.Generic.List<PwC.C4.DataService.Model.InvitationRole> invitationRoles);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfrastructure/InsertInvitation", ReplyAction="http://tempuri.org/IInfrastructure/InsertInvitationResponse")]
    System.Threading.Tasks.Task<string> InsertInvitationAsync(PwC.C4.DataService.Model.Invitation invitation, System.Collections.Generic.List<PwC.C4.DataService.Model.InvitationRole> invitationRoles);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IInfrastructureChannel : IInfrastructure, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InfrastructureClient : System.ServiceModel.ClientBase<IInfrastructure>, IInfrastructure
{
    
    public InfrastructureClient()
    {
    }
    
    public InfrastructureClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InfrastructureClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InfrastructureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InfrastructureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int InsertToMailQueue(PwC.C4.DataService.Model.MailQueueModel model)
    {
        return base.Channel.InsertToMailQueue(model);
    }
    
    public System.Threading.Tasks.Task<int> InsertToMailQueueAsync(PwC.C4.DataService.Model.MailQueueModel model)
    {
        return base.Channel.InsertToMailQueueAsync(model);
    }
    
    public int InsertToMailQueueBatch(System.Collections.Generic.List<PwC.C4.DataService.Model.MailQueueModel> model)
    {
        return base.Channel.InsertToMailQueueBatch(model);
    }
    
    public System.Threading.Tasks.Task<int> InsertToMailQueueBatchAsync(System.Collections.Generic.List<PwC.C4.DataService.Model.MailQueueModel> model)
    {
        return base.Channel.InsertToMailQueueBatchAsync(model);
    }
    
    public PwC.C4.DataService.Model.StaffInfo Staff_Get(string staffId)
    {
        return base.Channel.Staff_Get(staffId);
    }
    
    public System.Threading.Tasks.Task<PwC.C4.DataService.Model.StaffInfo> Staff_GetAsync(string staffId)
    {
        return base.Channel.Staff_GetAsync(staffId);
    }
    
    public string InsertInvitation(PwC.C4.DataService.Model.Invitation invitation, System.Collections.Generic.List<PwC.C4.DataService.Model.InvitationRole> invitationRoles)
    {
        return base.Channel.InsertInvitation(invitation, invitationRoles);
    }
    
    public System.Threading.Tasks.Task<string> InsertInvitationAsync(PwC.C4.DataService.Model.Invitation invitation, System.Collections.Generic.List<PwC.C4.DataService.Model.InvitationRole> invitationRoles)
    {
        return base.Channel.InsertInvitationAsync(invitation, invitationRoles);
    }
}
