//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PwC.C4.Rush.WcfService.Models.Enum
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ControlType", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.Rush.WcfService.Models.Enum")]
    public enum ControlType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Section = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Control = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Html = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Separator = 3,
    }
}
namespace PwC.C4.Rush.WcfService.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormMain", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.Rush.WcfService.Models")]
    public partial class FormMain : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AliasNameField;
        
        private string ConnNameField;
        
        private string CreateByField;
        
        private System.DateTime CreateTimeField;
        
        private string EntityNameField;
        
        private string FormNameField;
        
        private System.Guid IdField;
        
        private bool IsDeletedField;
        
        private string JavaScriptField;
        
        private System.Guid LayoutField;
        
        private string LayoutCodeField;
        
        private string LayoutNameField;
        
        private string LinkTrackingConnNameField;
        
        private string ModifyByField;
        
        private System.DateTime ModifyTimeField;
        
        private string PropsField;
        
        private int StatusField;
        
        private string StructureField;
        
        private string StylesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliasName
        {
            get
            {
                return this.AliasNameField;
            }
            set
            {
                this.AliasNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnName
        {
            get
            {
                return this.ConnNameField;
            }
            set
            {
                this.ConnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBy
        {
            get
            {
                return this.CreateByField;
            }
            set
            {
                this.CreateByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityName
        {
            get
            {
                return this.EntityNameField;
            }
            set
            {
                this.EntityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormName
        {
            get
            {
                return this.FormNameField;
            }
            set
            {
                this.FormNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JavaScript
        {
            get
            {
                return this.JavaScriptField;
            }
            set
            {
                this.JavaScriptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Layout
        {
            get
            {
                return this.LayoutField;
            }
            set
            {
                this.LayoutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LayoutCode
        {
            get
            {
                return this.LayoutCodeField;
            }
            set
            {
                this.LayoutCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LayoutName
        {
            get
            {
                return this.LayoutNameField;
            }
            set
            {
                this.LayoutNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkTrackingConnName
        {
            get
            {
                return this.LinkTrackingConnNameField;
            }
            set
            {
                this.LinkTrackingConnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyBy
        {
            get
            {
                return this.ModifyByField;
            }
            set
            {
                this.ModifyByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyTime
        {
            get
            {
                return this.ModifyTimeField;
            }
            set
            {
                this.ModifyTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Props
        {
            get
            {
                return this.PropsField;
            }
            set
            {
                this.PropsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Structure
        {
            get
            {
                return this.StructureField;
            }
            set
            {
                this.StructureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Styles
        {
            get
            {
                return this.StylesField;
            }
            set
            {
                this.StylesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormLayout", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.Rush.WcfService.Models")]
    public partial class FormLayout : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string HtmlField;
        
        private System.Guid IdField;
        
        private bool IsDeletedField;
        
        private string NameField;
        
        private int StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Html
        {
            get
            {
                return this.HtmlField;
            }
            set
            {
                this.HtmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FromRender", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.Rush.WcfService.Models")]
    public partial class FromRender : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormControl> ControlsField;
        
        private System.Collections.Generic.Dictionary<string, object> DataField;
        
        private string FormNameField;
        
        private string JavascriptsField;
        
        private string LayoutField;
        
        private string StylesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormControl> Controls
        {
            get
            {
                return this.ControlsField;
            }
            set
            {
                this.ControlsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormName
        {
            get
            {
                return this.FormNameField;
            }
            set
            {
                this.FormNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Javascripts
        {
            get
            {
                return this.JavascriptsField;
            }
            set
            {
                this.JavascriptsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Layout
        {
            get
            {
                return this.LayoutField;
            }
            set
            {
                this.LayoutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Styles
        {
            get
            {
                return this.StylesField;
            }
            set
            {
                this.StylesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormControl", Namespace="http://schemas.datacontract.org/2004/07/PwC.C4.Rush.WcfService.Models")]
    public partial class FormControl : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PwC.C4.Rush.WcfService.Models.Enum.ControlType ControlTypeField;
        
        private string GridSystemField;
        
        private string LabelField;
        
        private string LabelTemplateField;
        
        private string NameField;
        
        private string ParametersField;
        
        private System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormControl> SubFormDesginsField;
        
        private string ValueTemplateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PwC.C4.Rush.WcfService.Models.Enum.ControlType ControlType
        {
            get
            {
                return this.ControlTypeField;
            }
            set
            {
                this.ControlTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GridSystem
        {
            get
            {
                return this.GridSystemField;
            }
            set
            {
                this.GridSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                this.LabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelTemplate
        {
            get
            {
                return this.LabelTemplateField;
            }
            set
            {
                this.LabelTemplateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormControl> SubFormDesgins
        {
            get
            {
                return this.SubFormDesginsField;
            }
            set
            {
                this.SubFormDesginsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueTemplate
        {
            get
            {
                return this.ValueTemplateField;
            }
            set
            {
                this.ValueTemplateField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRushService")]
public interface IRushService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/DownloadContentFile", ReplyAction="http://tempuri.org/IRushService/DownloadContentFileResponse")]
    System.Tuple<string, string, System.IO.MemoryStream> DownloadContentFile(string aliasName, string fileid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/DownloadContentFile", ReplyAction="http://tempuri.org/IRushService/DownloadContentFileResponse")]
    System.Threading.Tasks.Task<System.Tuple<string, string, System.IO.MemoryStream>> DownloadContentFileAsync(string aliasName, string fileid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/GetLinkTrackingUrl", ReplyAction="http://tempuri.org/IRushService/GetLinkTrackingUrlResponse")]
    string GetLinkTrackingUrl(string notesUrl);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/GetLinkTrackingUrl", ReplyAction="http://tempuri.org/IRushService/GetLinkTrackingUrlResponse")]
    System.Threading.Tasks.Task<string> GetLinkTrackingUrlAsync(string notesUrl);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/DownloadFile", ReplyAction="http://tempuri.org/IRushService/DownloadFileResponse")]
    System.Tuple<string, string, System.IO.MemoryStream> DownloadFile(string aliasName, string fileid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/DownloadFile", ReplyAction="http://tempuri.org/IRushService/DownloadFileResponse")]
    System.Threading.Tasks.Task<System.Tuple<string, string, System.IO.MemoryStream>> DownloadFileAsync(string aliasName, string fileid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/GetFormList", ReplyAction="http://tempuri.org/IRushService/GetFormListResponse")]
    GetFormListResponse GetFormList(GetFormListRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/GetFormList", ReplyAction="http://tempuri.org/IRushService/GetFormListResponse")]
    System.Threading.Tasks.Task<GetFormListResponse> GetFormListAsync(GetFormListRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/GetFormBaseInfo", ReplyAction="http://tempuri.org/IRushService/GetFormBaseInfoResponse")]
    PwC.C4.Rush.WcfService.Models.FormMain GetFormBaseInfo(System.Guid formId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/GetFormBaseInfo", ReplyAction="http://tempuri.org/IRushService/GetFormBaseInfoResponse")]
    System.Threading.Tasks.Task<PwC.C4.Rush.WcfService.Models.FormMain> GetFormBaseInfoAsync(System.Guid formId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/GetFormLayoutList", ReplyAction="http://tempuri.org/IRushService/GetFormLayoutListResponse")]
    System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormLayout> GetFormLayoutList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/GetFormLayoutList", ReplyAction="http://tempuri.org/IRushService/GetFormLayoutListResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormLayout>> GetFormLayoutListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/DeleteFormBaseInfo", ReplyAction="http://tempuri.org/IRushService/DeleteFormBaseInfoResponse")]
    int DeleteFormBaseInfo(System.Guid formId, string modifyBy);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/DeleteFormBaseInfo", ReplyAction="http://tempuri.org/IRushService/DeleteFormBaseInfoResponse")]
    System.Threading.Tasks.Task<int> DeleteFormBaseInfoAsync(System.Guid formId, string modifyBy);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/SaveFormBaseInfo", ReplyAction="http://tempuri.org/IRushService/SaveFormBaseInfoResponse")]
    System.Guid SaveFormBaseInfo(PwC.C4.Rush.WcfService.Models.FormMain form);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/SaveFormBaseInfo", ReplyAction="http://tempuri.org/IRushService/SaveFormBaseInfoResponse")]
    System.Threading.Tasks.Task<System.Guid> SaveFormBaseInfoAsync(PwC.C4.Rush.WcfService.Models.FormMain form);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/RenderForm", ReplyAction="http://tempuri.org/IRushService/RenderFormResponse")]
    PwC.C4.Rush.WcfService.Models.FromRender RenderForm(string dataId, string aliasName, string prop);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/RenderForm", ReplyAction="http://tempuri.org/IRushService/RenderFormResponse")]
    System.Threading.Tasks.Task<PwC.C4.Rush.WcfService.Models.FromRender> RenderFormAsync(string dataId, string aliasName, string prop);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/UpdateStructure", ReplyAction="http://tempuri.org/IRushService/UpdateStructureResponse")]
    int UpdateStructure(System.Guid formId, string userId, string prop, string javascript, string styles, System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormControl> formControls);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRushService/UpdateStructure", ReplyAction="http://tempuri.org/IRushService/UpdateStructureResponse")]
    System.Threading.Tasks.Task<int> UpdateStructureAsync(System.Guid formId, string userId, string prop, string javascript, string styles, System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormControl> formControls);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetFormList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetFormListRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string keyword;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public int page;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public int rows;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
    public string sort;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
    public string order;
    
    public GetFormListRequest()
    {
    }
    
    public GetFormListRequest(string keyword, int page, int rows, string sort, string order)
    {
        this.keyword = keyword;
        this.page = page;
        this.rows = rows;
        this.sort = sort;
        this.order = order;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetFormListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetFormListResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormMain> GetFormListResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public int totalCount;
    
    public GetFormListResponse()
    {
    }
    
    public GetFormListResponse(System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormMain> GetFormListResult, int totalCount)
    {
        this.GetFormListResult = GetFormListResult;
        this.totalCount = totalCount;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRushServiceChannel : IRushService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RushServiceClient : System.ServiceModel.ClientBase<IRushService>, IRushService
{
    
    public RushServiceClient()
    {
    }
    
    public RushServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RushServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RushServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RushServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Tuple<string, string, System.IO.MemoryStream> DownloadContentFile(string aliasName, string fileid)
    {
        return base.Channel.DownloadContentFile(aliasName, fileid);
    }
    
    public System.Threading.Tasks.Task<System.Tuple<string, string, System.IO.MemoryStream>> DownloadContentFileAsync(string aliasName, string fileid)
    {
        return base.Channel.DownloadContentFileAsync(aliasName, fileid);
    }
    
    public string GetLinkTrackingUrl(string notesUrl)
    {
        return base.Channel.GetLinkTrackingUrl(notesUrl);
    }
    
    public System.Threading.Tasks.Task<string> GetLinkTrackingUrlAsync(string notesUrl)
    {
        return base.Channel.GetLinkTrackingUrlAsync(notesUrl);
    }
    
    public System.Tuple<string, string, System.IO.MemoryStream> DownloadFile(string aliasName, string fileid)
    {
        return base.Channel.DownloadFile(aliasName, fileid);
    }
    
    public System.Threading.Tasks.Task<System.Tuple<string, string, System.IO.MemoryStream>> DownloadFileAsync(string aliasName, string fileid)
    {
        return base.Channel.DownloadFileAsync(aliasName, fileid);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetFormListResponse IRushService.GetFormList(GetFormListRequest request)
    {
        return base.Channel.GetFormList(request);
    }
    
    public System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormMain> GetFormList(string keyword, int page, int rows, string sort, string order, out int totalCount)
    {
        GetFormListRequest inValue = new GetFormListRequest();
        inValue.keyword = keyword;
        inValue.page = page;
        inValue.rows = rows;
        inValue.sort = sort;
        inValue.order = order;
        GetFormListResponse retVal = ((IRushService)(this)).GetFormList(inValue);
        totalCount = retVal.totalCount;
        return retVal.GetFormListResult;
    }
    
    public System.Threading.Tasks.Task<GetFormListResponse> GetFormListAsync(GetFormListRequest request)
    {
        return base.Channel.GetFormListAsync(request);
    }
    
    public PwC.C4.Rush.WcfService.Models.FormMain GetFormBaseInfo(System.Guid formId)
    {
        return base.Channel.GetFormBaseInfo(formId);
    }
    
    public System.Threading.Tasks.Task<PwC.C4.Rush.WcfService.Models.FormMain> GetFormBaseInfoAsync(System.Guid formId)
    {
        return base.Channel.GetFormBaseInfoAsync(formId);
    }
    
    public System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormLayout> GetFormLayoutList()
    {
        return base.Channel.GetFormLayoutList();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormLayout>> GetFormLayoutListAsync()
    {
        return base.Channel.GetFormLayoutListAsync();
    }
    
    public int DeleteFormBaseInfo(System.Guid formId, string modifyBy)
    {
        return base.Channel.DeleteFormBaseInfo(formId, modifyBy);
    }
    
    public System.Threading.Tasks.Task<int> DeleteFormBaseInfoAsync(System.Guid formId, string modifyBy)
    {
        return base.Channel.DeleteFormBaseInfoAsync(formId, modifyBy);
    }
    
    public System.Guid SaveFormBaseInfo(PwC.C4.Rush.WcfService.Models.FormMain form)
    {
        return base.Channel.SaveFormBaseInfo(form);
    }
    
    public System.Threading.Tasks.Task<System.Guid> SaveFormBaseInfoAsync(PwC.C4.Rush.WcfService.Models.FormMain form)
    {
        return base.Channel.SaveFormBaseInfoAsync(form);
    }
    
    public PwC.C4.Rush.WcfService.Models.FromRender RenderForm(string dataId, string aliasName, string prop)
    {
        return base.Channel.RenderForm(dataId, aliasName, prop);
    }
    
    public System.Threading.Tasks.Task<PwC.C4.Rush.WcfService.Models.FromRender> RenderFormAsync(string dataId, string aliasName, string prop)
    {
        return base.Channel.RenderFormAsync(dataId, aliasName, prop);
    }
    
    public int UpdateStructure(System.Guid formId, string userId, string prop, string javascript, string styles, System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormControl> formControls)
    {
        return base.Channel.UpdateStructure(formId, userId, prop, javascript, styles, formControls);
    }
    
    public System.Threading.Tasks.Task<int> UpdateStructureAsync(System.Guid formId, string userId, string prop, string javascript, string styles, System.Collections.Generic.List<PwC.C4.Rush.WcfService.Models.FormControl> formControls)
    {
        return base.Channel.UpdateStructureAsync(formId, userId, prop, javascript, styles, formControls);
    }
}
